from typing import TYPE_CHECKING

from sqlalchemy import Date, Float, Integer, String, Numeric, DateTime
from sqlalchemy.orm import Mapped, mapped_column, relationship

from efficieno.components.erd_objects import ERDBase, ColumnMetadata



class QDiDomesticHeatingV(ERDBase):
    __data_object_type__ = "data_object"
    __tablename__ = "q_di_domestic_heating_v"
    __table_args__ = {"schema": "apps", "extend_existing": True}
    __table_properties__ = {"ui_x_pos": 0, "ui_y_pos": 0, "colour": "#F2F3F5"}

    plan_id: Mapped[str] = mapped_column('plan_id', Numeric, primary_key=True, info={"column_metadata": ColumnMetadata()})
    plan_name: Mapped[str] = mapped_column('plan_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    organization_id: Mapped[str] = mapped_column('organization_id', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    organization_name: Mapped[str] = mapped_column('organization_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    collection_id: Mapped[str] = mapped_column('collection_id', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    occurrence: Mapped[str] = mapped_column('occurrence', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_update_date: Mapped[str] = mapped_column('last_update_date', DateTime, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_updated_by_id: Mapped[str] = mapped_column('last_updated_by_id', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_updated_by: Mapped[str] = mapped_column('last_updated_by', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    creation_date: Mapped[str] = mapped_column('creation_date', DateTime, primary_key=False, info={"column_metadata": ColumnMetadata()})
    created_by_id: Mapped[str] = mapped_column('created_by_id', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    created_by: Mapped[str] = mapped_column('created_by', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_update_login: Mapped[str] = mapped_column('last_update_login', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    operating_unit: Mapped[str] = mapped_column('operating_unit', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    di_number: Mapped[str] = mapped_column('di_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    sales_order_no: Mapped[str] = mapped_column('sales_order_no', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    customer_id: Mapped[str] = mapped_column('customer_id', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    customer: Mapped[str] = mapped_column('customer', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    xx_project_number: Mapped[str] = mapped_column('xx_project_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    region_zone: Mapped[str] = mapped_column('region_zone', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    area_country: Mapped[str] = mapped_column('area_country', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    partial_shipment_instructions: Mapped[str] = mapped_column('partial_shipment_instructions', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    bill_to_address: Mapped[str] = mapped_column('bill_to_address', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    bill_to_customer_person_name: Mapped[str] = mapped_column('bill_to_customer_person_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_to_address: Mapped[str] = mapped_column('ship_to_address', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_to_customer_name: Mapped[str] = mapped_column('ship_to_customer_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tin_no: Mapped[str] = mapped_column('tin_no', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cust_ecc_no: Mapped[str] = mapped_column('cust_ecc_no', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cst_no: Mapped[str] = mapped_column('cst_no', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    epcg_licence_number_date: Mapped[str] = mapped_column('epcg_licence_number_date', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    contact_person: Mapped[str] = mapped_column('contact_person', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    contact_number: Mapped[str] = mapped_column('contact_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    fax: Mapped[str] = mapped_column('fax', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    email_address: Mapped[str] = mapped_column('email_address', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    receiver: Mapped[str] = mapped_column('receiver', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    payment_amount: Mapped[str] = mapped_column('payment_amount', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    br_cheque_number: Mapped[str] = mapped_column('br_cheque_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    br_cheque_date: Mapped[str] = mapped_column('br_cheque_date', DateTime, primary_key=False, info={"column_metadata": ColumnMetadata()})
    recommended_transporter: Mapped[str] = mapped_column('recommended_transporter', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    freight: Mapped[str] = mapped_column('freight', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    consignment_delivery_instructn: Mapped[str] = mapped_column('consignment_delivery_instructn', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shipping_method: Mapped[str] = mapped_column('shipping_method', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    MODE: Mapped[str] = mapped_column('MODE', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    road_permit_status: Mapped[str] = mapped_column('road_permit_status', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    payment_details1: Mapped[str] = mapped_column('payment_details1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amt1: Mapped[str] = mapped_column('amt1', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    payment_details2: Mapped[str] = mapped_column('payment_details2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amt2: Mapped[str] = mapped_column('amt2', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    payment_details3: Mapped[str] = mapped_column('payment_details3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amt3: Mapped[str] = mapped_column('amt3', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    payment_details4: Mapped[str] = mapped_column('payment_details4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amt4: Mapped[str] = mapped_column('amt4', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    total_amount: Mapped[str] = mapped_column('total_amount', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    particulars1: Mapped[str] = mapped_column('particulars1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    qty1: Mapped[str] = mapped_column('qty1', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amt6: Mapped[str] = mapped_column('amt6', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    particulars2: Mapped[str] = mapped_column('particulars2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    qty2: Mapped[str] = mapped_column('qty2', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amt7: Mapped[str] = mapped_column('amt7', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    particulars3: Mapped[str] = mapped_column('particulars3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    qty3: Mapped[str] = mapped_column('qty3', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amt8: Mapped[str] = mapped_column('amt8', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    particulars4: Mapped[str] = mapped_column('particulars4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    qty4: Mapped[str] = mapped_column('qty4', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amt12: Mapped[str] = mapped_column('amt12', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    particulars5: Mapped[str] = mapped_column('particulars5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    qty5: Mapped[str] = mapped_column('qty5', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amt14: Mapped[str] = mapped_column('amt14', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    particulars6: Mapped[str] = mapped_column('particulars6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    qty6: Mapped[str] = mapped_column('qty6', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amt15: Mapped[str] = mapped_column('amt15', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    particulars7: Mapped[str] = mapped_column('particulars7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    qty7: Mapped[str] = mapped_column('qty7', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amt16: Mapped[str] = mapped_column('amt16', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    basic_amount: Mapped[str] = mapped_column('basic_amount', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    packing__forwarding_amount: Mapped[str] = mapped_column('packing__forwarding_amount', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    excisable_amount: Mapped[str] = mapped_column('excisable_amount', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    excise__duty: Mapped[str] = mapped_column('excise__duty', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amt17: Mapped[str] = mapped_column('amt17', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cess_on_excise__duty: Mapped[str] = mapped_column('cess_on_excise__duty', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amt9: Mapped[str] = mapped_column('amt9', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    s_h_cess_on_excise__duty: Mapped[str] = mapped_column('s_h_cess_on_excise__duty', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amt10: Mapped[str] = mapped_column('amt10', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    insurance_charges: Mapped[str] = mapped_column('insurance_charges', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    taxable_amount: Mapped[str] = mapped_column('taxable_amount', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cst: Mapped[str] = mapped_column('cst', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amt5: Mapped[str] = mapped_column('amt5', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    vat: Mapped[str] = mapped_column('vat', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amt13: Mapped[str] = mapped_column('amt13', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    full_taxes: Mapped[str] = mapped_column('full_taxes', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amt11: Mapped[str] = mapped_column('amt11', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    freight_amount: Mapped[str] = mapped_column('freight_amount', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_tax: Mapped[str] = mapped_column('service_tax', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_tax_amount: Mapped[str] = mapped_column('service_tax_amount', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    gross_amount: Mapped[str] = mapped_column('gross_amount', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    unloading_by: Mapped[str] = mapped_column('unloading_by', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    any_special_instruction: Mapped[str] = mapped_column('any_special_instruction', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    send_email: Mapped[str] = mapped_column('send_email', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cgst: Mapped[str] = mapped_column('cgst', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cgst_percentage: Mapped[str] = mapped_column('cgst_percentage', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})
    sgst: Mapped[str] = mapped_column('sgst', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    sgst_percentage: Mapped[str] = mapped_column('sgst_percentage', Numeric, primary_key=False, info={"column_metadata": ColumnMetadata()})




