from typing import TYPE_CHECKING

from sqlalchemy import Date, Float, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from efficieno.components.erd_objects import ERDBase, ColumnMetadata

if TYPE_CHECKING:
    from ..apps.org_organization_definitions import OrgOrganizationDefinitions
    from ..inv.mtl_system_items_b import MtlSystemItemsB
    from ..inv.mtl_system_items_b import MtlSystemItemsB
    from ..wsh.wsh_delivery_details import WshDeliveryDetails
    from ..ont.oe_order_headers_all import OeOrderHeadersAll


class OeOrderLinesAll(ERDBase):
    __data_object_type__ = "data_object"
    __tablename__ = "oe_order_lines_all"
    __table_args__ = {"schema": "ont", "extend_existing": True}
    __table_properties__ = {"ui_x_pos": 1592.8001763453558, "ui_y_pos": 170.4615975331826, "colour": "#F2F3F5"}

    line_id: Mapped[str] = mapped_column('line_id', Integer, primary_key=True, info={"column_metadata": ColumnMetadata()})
    org_id: Mapped[str] = mapped_column('org_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    header_id: Mapped[str] = mapped_column('header_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    line_type_id: Mapped[str] = mapped_column('line_type_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    line_number: Mapped[str] = mapped_column('line_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ordered_item: Mapped[str] = mapped_column('ordered_item', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    request_date: Mapped[str] = mapped_column('request_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    promise_date: Mapped[str] = mapped_column('promise_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    schedule_ship_date: Mapped[str] = mapped_column('schedule_ship_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    order_quantity_uom: Mapped[str] = mapped_column('order_quantity_uom', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pricing_quantity: Mapped[str] = mapped_column('pricing_quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pricing_quantity_uom: Mapped[str] = mapped_column('pricing_quantity_uom', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cancelled_quantity: Mapped[str] = mapped_column('cancelled_quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shipped_quantity: Mapped[str] = mapped_column('shipped_quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ordered_quantity: Mapped[str] = mapped_column('ordered_quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    fulfilled_quantity: Mapped[str] = mapped_column('fulfilled_quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shipping_quantity: Mapped[str] = mapped_column('shipping_quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shipping_quantity_uom: Mapped[str] = mapped_column('shipping_quantity_uom', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    delivery_lead_time: Mapped[str] = mapped_column('delivery_lead_time', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_exempt_flag: Mapped[str] = mapped_column('tax_exempt_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_exempt_number: Mapped[str] = mapped_column('tax_exempt_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_exempt_reason_code: Mapped[str] = mapped_column('tax_exempt_reason_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_from_org_id: Mapped[str] = mapped_column('ship_from_org_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_to_org_id: Mapped[str] = mapped_column('ship_to_org_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    invoice_to_org_id: Mapped[str] = mapped_column('invoice_to_org_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    deliver_to_org_id: Mapped[str] = mapped_column('deliver_to_org_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_to_contact_id: Mapped[str] = mapped_column('ship_to_contact_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    deliver_to_contact_id: Mapped[str] = mapped_column('deliver_to_contact_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    invoice_to_contact_id: Mapped[str] = mapped_column('invoice_to_contact_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    intmed_ship_to_org_id: Mapped[str] = mapped_column('intmed_ship_to_org_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    intmed_ship_to_contact_id: Mapped[str] = mapped_column('intmed_ship_to_contact_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    sold_from_org_id: Mapped[str] = mapped_column('sold_from_org_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    sold_to_org_id: Mapped[str] = mapped_column('sold_to_org_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cust_po_number: Mapped[str] = mapped_column('cust_po_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_tolerance_above: Mapped[str] = mapped_column('ship_tolerance_above', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_tolerance_below: Mapped[str] = mapped_column('ship_tolerance_below', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    demand_bucket_type_code: Mapped[str] = mapped_column('demand_bucket_type_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    veh_cus_item_cum_key_id: Mapped[str] = mapped_column('veh_cus_item_cum_key_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    rla_schedule_type_code: Mapped[str] = mapped_column('rla_schedule_type_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    customer_dock_code: Mapped[str] = mapped_column('customer_dock_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    customer_job: Mapped[str] = mapped_column('customer_job', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    customer_production_line: Mapped[str] = mapped_column('customer_production_line', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cust_model_serial_number: Mapped[str] = mapped_column('cust_model_serial_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    project_id: Mapped[str] = mapped_column('project_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    task_id: Mapped[str] = mapped_column('task_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    inventory_item_id: Mapped[str] = mapped_column('inventory_item_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_date: Mapped[str] = mapped_column('tax_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_code: Mapped[str] = mapped_column('tax_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_rate: Mapped[str] = mapped_column('tax_rate', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    invoice_interface_status_code: Mapped[str] = mapped_column('invoice_interface_status_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    demand_class_code: Mapped[str] = mapped_column('demand_class_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    price_list_id: Mapped[str] = mapped_column('price_list_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pricing_date: Mapped[str] = mapped_column('pricing_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shipment_number: Mapped[str] = mapped_column('shipment_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    agreement_id: Mapped[str] = mapped_column('agreement_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shipment_priority_code: Mapped[str] = mapped_column('shipment_priority_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shipping_method_code: Mapped[str] = mapped_column('shipping_method_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    freight_carrier_code: Mapped[str] = mapped_column('freight_carrier_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    freight_terms_code: Mapped[str] = mapped_column('freight_terms_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    fob_point_code: Mapped[str] = mapped_column('fob_point_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_point_code: Mapped[str] = mapped_column('tax_point_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    payment_term_id: Mapped[str] = mapped_column('payment_term_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    invoicing_rule_id: Mapped[str] = mapped_column('invoicing_rule_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    accounting_rule_id: Mapped[str] = mapped_column('accounting_rule_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    source_document_type_id: Mapped[str] = mapped_column('source_document_type_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    orig_sys_document_ref: Mapped[str] = mapped_column('orig_sys_document_ref', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    source_document_id: Mapped[str] = mapped_column('source_document_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    orig_sys_line_ref: Mapped[str] = mapped_column('orig_sys_line_ref', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    source_document_line_id: Mapped[str] = mapped_column('source_document_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    reference_line_id: Mapped[str] = mapped_column('reference_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    reference_type: Mapped[str] = mapped_column('reference_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    reference_header_id: Mapped[str] = mapped_column('reference_header_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    item_revision: Mapped[str] = mapped_column('item_revision', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    unit_selling_price: Mapped[str] = mapped_column('unit_selling_price', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    unit_list_price: Mapped[str] = mapped_column('unit_list_price', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_value: Mapped[str] = mapped_column('tax_value', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    context: Mapped[str] = mapped_column('context', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute1: Mapped[str] = mapped_column('attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute2: Mapped[str] = mapped_column('attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute3: Mapped[str] = mapped_column('attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute4: Mapped[str] = mapped_column('attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute5: Mapped[str] = mapped_column('attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute6: Mapped[str] = mapped_column('attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute7: Mapped[str] = mapped_column('attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute8: Mapped[str] = mapped_column('attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute9: Mapped[str] = mapped_column('attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute10: Mapped[str] = mapped_column('attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute11: Mapped[str] = mapped_column('attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute12: Mapped[str] = mapped_column('attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute13: Mapped[str] = mapped_column('attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute14: Mapped[str] = mapped_column('attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute15: Mapped[str] = mapped_column('attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute_category: Mapped[str] = mapped_column('global_attribute_category', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute1: Mapped[str] = mapped_column('global_attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute2: Mapped[str] = mapped_column('global_attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute3: Mapped[str] = mapped_column('global_attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute4: Mapped[str] = mapped_column('global_attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute5: Mapped[str] = mapped_column('global_attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute6: Mapped[str] = mapped_column('global_attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute7: Mapped[str] = mapped_column('global_attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute8: Mapped[str] = mapped_column('global_attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute9: Mapped[str] = mapped_column('global_attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute10: Mapped[str] = mapped_column('global_attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute11: Mapped[str] = mapped_column('global_attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute12: Mapped[str] = mapped_column('global_attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute13: Mapped[str] = mapped_column('global_attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute14: Mapped[str] = mapped_column('global_attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute15: Mapped[str] = mapped_column('global_attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute16: Mapped[str] = mapped_column('global_attribute16', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute17: Mapped[str] = mapped_column('global_attribute17', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute18: Mapped[str] = mapped_column('global_attribute18', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute19: Mapped[str] = mapped_column('global_attribute19', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute20: Mapped[str] = mapped_column('global_attribute20', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pricing_context: Mapped[str] = mapped_column('pricing_context', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pricing_attribute1: Mapped[str] = mapped_column('pricing_attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pricing_attribute2: Mapped[str] = mapped_column('pricing_attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pricing_attribute3: Mapped[str] = mapped_column('pricing_attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pricing_attribute4: Mapped[str] = mapped_column('pricing_attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pricing_attribute5: Mapped[str] = mapped_column('pricing_attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pricing_attribute6: Mapped[str] = mapped_column('pricing_attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pricing_attribute7: Mapped[str] = mapped_column('pricing_attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pricing_attribute8: Mapped[str] = mapped_column('pricing_attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pricing_attribute9: Mapped[str] = mapped_column('pricing_attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pricing_attribute10: Mapped[str] = mapped_column('pricing_attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_context: Mapped[str] = mapped_column('industry_context', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute1: Mapped[str] = mapped_column('industry_attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute2: Mapped[str] = mapped_column('industry_attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute3: Mapped[str] = mapped_column('industry_attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute4: Mapped[str] = mapped_column('industry_attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute5: Mapped[str] = mapped_column('industry_attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute6: Mapped[str] = mapped_column('industry_attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute7: Mapped[str] = mapped_column('industry_attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute8: Mapped[str] = mapped_column('industry_attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute9: Mapped[str] = mapped_column('industry_attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute10: Mapped[str] = mapped_column('industry_attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute11: Mapped[str] = mapped_column('industry_attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute13: Mapped[str] = mapped_column('industry_attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute12: Mapped[str] = mapped_column('industry_attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute14: Mapped[str] = mapped_column('industry_attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute15: Mapped[str] = mapped_column('industry_attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute16: Mapped[str] = mapped_column('industry_attribute16', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute17: Mapped[str] = mapped_column('industry_attribute17', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute18: Mapped[str] = mapped_column('industry_attribute18', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute19: Mapped[str] = mapped_column('industry_attribute19', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute20: Mapped[str] = mapped_column('industry_attribute20', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute21: Mapped[str] = mapped_column('industry_attribute21', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute22: Mapped[str] = mapped_column('industry_attribute22', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute23: Mapped[str] = mapped_column('industry_attribute23', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute24: Mapped[str] = mapped_column('industry_attribute24', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute25: Mapped[str] = mapped_column('industry_attribute25', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute26: Mapped[str] = mapped_column('industry_attribute26', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute27: Mapped[str] = mapped_column('industry_attribute27', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute28: Mapped[str] = mapped_column('industry_attribute28', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute29: Mapped[str] = mapped_column('industry_attribute29', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    industry_attribute30: Mapped[str] = mapped_column('industry_attribute30', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    creation_date: Mapped[str] = mapped_column('creation_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    created_by: Mapped[str] = mapped_column('created_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_update_date: Mapped[str] = mapped_column('last_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_updated_by: Mapped[str] = mapped_column('last_updated_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_update_login: Mapped[str] = mapped_column('last_update_login', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_application_id: Mapped[str] = mapped_column('program_application_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_id: Mapped[str] = mapped_column('program_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_update_date: Mapped[str] = mapped_column('program_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    request_id: Mapped[str] = mapped_column('request_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    top_model_line_id: Mapped[str] = mapped_column('top_model_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    link_to_line_id: Mapped[str] = mapped_column('link_to_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    component_sequence_id: Mapped[str] = mapped_column('component_sequence_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    component_code: Mapped[str] = mapped_column('component_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    config_display_sequence: Mapped[str] = mapped_column('config_display_sequence', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    sort_order: Mapped[str] = mapped_column('sort_order', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    item_type_code: Mapped[str] = mapped_column('item_type_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    option_number: Mapped[str] = mapped_column('option_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    option_flag: Mapped[str] = mapped_column('option_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    dep_plan_required_flag: Mapped[str] = mapped_column('dep_plan_required_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    visible_demand_flag: Mapped[str] = mapped_column('visible_demand_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    line_category_code: Mapped[str] = mapped_column('line_category_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    actual_shipment_date: Mapped[str] = mapped_column('actual_shipment_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    customer_trx_line_id: Mapped[str] = mapped_column('customer_trx_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    return_context: Mapped[str] = mapped_column('return_context', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    return_attribute1: Mapped[str] = mapped_column('return_attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    return_attribute2: Mapped[str] = mapped_column('return_attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    return_attribute3: Mapped[str] = mapped_column('return_attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    return_attribute4: Mapped[str] = mapped_column('return_attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    return_attribute5: Mapped[str] = mapped_column('return_attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    return_attribute6: Mapped[str] = mapped_column('return_attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    return_attribute7: Mapped[str] = mapped_column('return_attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    return_attribute8: Mapped[str] = mapped_column('return_attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    return_attribute9: Mapped[str] = mapped_column('return_attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    return_attribute10: Mapped[str] = mapped_column('return_attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    return_attribute11: Mapped[str] = mapped_column('return_attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    return_attribute12: Mapped[str] = mapped_column('return_attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    return_attribute13: Mapped[str] = mapped_column('return_attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    return_attribute14: Mapped[str] = mapped_column('return_attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    return_attribute15: Mapped[str] = mapped_column('return_attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    actual_arrival_date: Mapped[str] = mapped_column('actual_arrival_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ato_line_id: Mapped[str] = mapped_column('ato_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    auto_selected_quantity: Mapped[str] = mapped_column('auto_selected_quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    component_number: Mapped[str] = mapped_column('component_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    earliest_acceptable_date: Mapped[str] = mapped_column('earliest_acceptable_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    explosion_date: Mapped[str] = mapped_column('explosion_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    latest_acceptable_date: Mapped[str] = mapped_column('latest_acceptable_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    model_group_number: Mapped[str] = mapped_column('model_group_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    schedule_arrival_date: Mapped[str] = mapped_column('schedule_arrival_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_model_complete_flag: Mapped[str] = mapped_column('ship_model_complete_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    schedule_status_code: Mapped[str] = mapped_column('schedule_status_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    source_type_code: Mapped[str] = mapped_column('source_type_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cancelled_flag: Mapped[str] = mapped_column('cancelled_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    open_flag: Mapped[str] = mapped_column('open_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    booked_flag: Mapped[str] = mapped_column('booked_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    salesrep_id: Mapped[str] = mapped_column('salesrep_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    return_reason_code: Mapped[str] = mapped_column('return_reason_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    arrival_set_id: Mapped[str] = mapped_column('arrival_set_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_set_id: Mapped[str] = mapped_column('ship_set_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    split_from_line_id: Mapped[str] = mapped_column('split_from_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cust_production_seq_num: Mapped[str] = mapped_column('cust_production_seq_num', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    authorized_to_ship_flag: Mapped[str] = mapped_column('authorized_to_ship_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    over_ship_reason_code: Mapped[str] = mapped_column('over_ship_reason_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    over_ship_resolved_flag: Mapped[str] = mapped_column('over_ship_resolved_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ordered_item_id: Mapped[str] = mapped_column('ordered_item_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    item_identifier_type: Mapped[str] = mapped_column('item_identifier_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    configuration_id: Mapped[str] = mapped_column('configuration_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    commitment_id: Mapped[str] = mapped_column('commitment_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shipping_interfaced_flag: Mapped[str] = mapped_column('shipping_interfaced_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    credit_invoice_line_id: Mapped[str] = mapped_column('credit_invoice_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    first_ack_code: Mapped[str] = mapped_column('first_ack_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    first_ack_date: Mapped[str] = mapped_column('first_ack_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_ack_code: Mapped[str] = mapped_column('last_ack_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_ack_date: Mapped[str] = mapped_column('last_ack_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    planning_priority: Mapped[str] = mapped_column('planning_priority', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    order_source_id: Mapped[str] = mapped_column('order_source_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    orig_sys_shipment_ref: Mapped[str] = mapped_column('orig_sys_shipment_ref', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    change_sequence: Mapped[str] = mapped_column('change_sequence', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    drop_ship_flag: Mapped[str] = mapped_column('drop_ship_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    customer_line_number: Mapped[str] = mapped_column('customer_line_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    customer_shipment_number: Mapped[str] = mapped_column('customer_shipment_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    customer_item_net_price: Mapped[str] = mapped_column('customer_item_net_price', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    customer_payment_term_id: Mapped[str] = mapped_column('customer_payment_term_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    fulfilled_flag: Mapped[str] = mapped_column('fulfilled_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    end_item_unit_number: Mapped[str] = mapped_column('end_item_unit_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    config_header_id: Mapped[str] = mapped_column('config_header_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    config_rev_nbr: Mapped[str] = mapped_column('config_rev_nbr', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    mfg_component_sequence_id: Mapped[str] = mapped_column('mfg_component_sequence_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shipping_instructions: Mapped[str] = mapped_column('shipping_instructions', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    packing_instructions: Mapped[str] = mapped_column('packing_instructions', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    invoiced_quantity: Mapped[str] = mapped_column('invoiced_quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    reference_customer_trx_line_id: Mapped[str] = mapped_column('reference_customer_trx_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    split_by: Mapped[str] = mapped_column('split_by', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    line_set_id: Mapped[str] = mapped_column('line_set_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_txn_reason_code: Mapped[str] = mapped_column('service_txn_reason_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_txn_comments: Mapped[str] = mapped_column('service_txn_comments', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_duration: Mapped[str] = mapped_column('service_duration', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_start_date: Mapped[str] = mapped_column('service_start_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_end_date: Mapped[str] = mapped_column('service_end_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_coterminate_flag: Mapped[str] = mapped_column('service_coterminate_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    unit_list_percent: Mapped[str] = mapped_column('unit_list_percent', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    unit_selling_percent: Mapped[str] = mapped_column('unit_selling_percent', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    unit_percent_base_price: Mapped[str] = mapped_column('unit_percent_base_price', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_number: Mapped[str] = mapped_column('service_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_period: Mapped[str] = mapped_column('service_period', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shippable_flag: Mapped[str] = mapped_column('shippable_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    model_remnant_flag: Mapped[str] = mapped_column('model_remnant_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    re_source_flag: Mapped[str] = mapped_column('re_source_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    flow_status_code: Mapped[str] = mapped_column('flow_status_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_context: Mapped[str] = mapped_column('tp_context', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute1: Mapped[str] = mapped_column('tp_attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute2: Mapped[str] = mapped_column('tp_attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute3: Mapped[str] = mapped_column('tp_attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute4: Mapped[str] = mapped_column('tp_attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute5: Mapped[str] = mapped_column('tp_attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute6: Mapped[str] = mapped_column('tp_attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute7: Mapped[str] = mapped_column('tp_attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute8: Mapped[str] = mapped_column('tp_attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute9: Mapped[str] = mapped_column('tp_attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute10: Mapped[str] = mapped_column('tp_attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute11: Mapped[str] = mapped_column('tp_attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute12: Mapped[str] = mapped_column('tp_attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute13: Mapped[str] = mapped_column('tp_attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute14: Mapped[str] = mapped_column('tp_attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute15: Mapped[str] = mapped_column('tp_attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    fulfillment_method_code: Mapped[str] = mapped_column('fulfillment_method_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    marketing_source_code_id: Mapped[str] = mapped_column('marketing_source_code_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_reference_type_code: Mapped[str] = mapped_column('service_reference_type_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_reference_line_id: Mapped[str] = mapped_column('service_reference_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_reference_system_id: Mapped[str] = mapped_column('service_reference_system_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    calculate_price_flag: Mapped[str] = mapped_column('calculate_price_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    upgraded_flag: Mapped[str] = mapped_column('upgraded_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    revenue_amount: Mapped[str] = mapped_column('revenue_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    fulfillment_date: Mapped[str] = mapped_column('fulfillment_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    preferred_grade: Mapped[str] = mapped_column('preferred_grade', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ordered_quantity2: Mapped[str] = mapped_column('ordered_quantity2', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ordered_quantity_uom2: Mapped[str] = mapped_column('ordered_quantity_uom2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shipping_quantity2: Mapped[str] = mapped_column('shipping_quantity2', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cancelled_quantity2: Mapped[str] = mapped_column('cancelled_quantity2', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shipped_quantity2: Mapped[str] = mapped_column('shipped_quantity2', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shipping_quantity_uom2: Mapped[str] = mapped_column('shipping_quantity_uom2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    fulfilled_quantity2: Mapped[str] = mapped_column('fulfilled_quantity2', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    mfg_lead_time: Mapped[str] = mapped_column('mfg_lead_time', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    lock_control: Mapped[str] = mapped_column('lock_control', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    subinventory: Mapped[str] = mapped_column('subinventory', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    unit_list_price_per_pqty: Mapped[str] = mapped_column('unit_list_price_per_pqty', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    unit_selling_price_per_pqty: Mapped[str] = mapped_column('unit_selling_price_per_pqty', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    price_request_code: Mapped[str] = mapped_column('price_request_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    original_inventory_item_id: Mapped[str] = mapped_column('original_inventory_item_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    original_ordered_item_id: Mapped[str] = mapped_column('original_ordered_item_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    original_ordered_item: Mapped[str] = mapped_column('original_ordered_item', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    original_item_identifier_type: Mapped[str] = mapped_column('original_item_identifier_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    item_substitution_type_code: Mapped[str] = mapped_column('item_substitution_type_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    override_atp_date_code: Mapped[str] = mapped_column('override_atp_date_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    late_demand_penalty_factor: Mapped[str] = mapped_column('late_demand_penalty_factor', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    accounting_rule_duration: Mapped[str] = mapped_column('accounting_rule_duration', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute16: Mapped[str] = mapped_column('attribute16', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute17: Mapped[str] = mapped_column('attribute17', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute18: Mapped[str] = mapped_column('attribute18', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute19: Mapped[str] = mapped_column('attribute19', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute20: Mapped[str] = mapped_column('attribute20', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    user_item_description: Mapped[str] = mapped_column('user_item_description', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    unit_cost: Mapped[str] = mapped_column('unit_cost', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    item_relationship_type: Mapped[str] = mapped_column('item_relationship_type', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    blanket_line_number: Mapped[str] = mapped_column('blanket_line_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    blanket_number: Mapped[str] = mapped_column('blanket_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    blanket_version_number: Mapped[str] = mapped_column('blanket_version_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    sales_document_type_code: Mapped[str] = mapped_column('sales_document_type_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    firm_demand_flag: Mapped[str] = mapped_column('firm_demand_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    earliest_ship_date: Mapped[str] = mapped_column('earliest_ship_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    transaction_phase_code: Mapped[str] = mapped_column('transaction_phase_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    source_document_version_number: Mapped[str] = mapped_column('source_document_version_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    payment_type_code: Mapped[str] = mapped_column('payment_type_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    minisite_id: Mapped[str] = mapped_column('minisite_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    end_customer_id: Mapped[str] = mapped_column('end_customer_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    end_customer_contact_id: Mapped[str] = mapped_column('end_customer_contact_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    end_customer_site_use_id: Mapped[str] = mapped_column('end_customer_site_use_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ib_owner: Mapped[str] = mapped_column('ib_owner', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    retrobill_request_id: Mapped[str] = mapped_column('retrobill_request_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    original_list_price: Mapped[str] = mapped_column('original_list_price', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_credit_eligible_code: Mapped[str] = mapped_column('service_credit_eligible_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    order_firmed_date: Mapped[str] = mapped_column('order_firmed_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    actual_fulfillment_date: Mapped[str] = mapped_column('actual_fulfillment_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    charge_periodicity_code: Mapped[str] = mapped_column('charge_periodicity_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    contingency_id: Mapped[str] = mapped_column('contingency_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    revrec_event_code: Mapped[str] = mapped_column('revrec_event_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    revrec_expiration_days: Mapped[str] = mapped_column('revrec_expiration_days', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    accepted_quantity: Mapped[str] = mapped_column('accepted_quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    accepted_by: Mapped[str] = mapped_column('accepted_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    revrec_comments: Mapped[str] = mapped_column('revrec_comments', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    revrec_reference_document: Mapped[str] = mapped_column('revrec_reference_document', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    revrec_signature: Mapped[str] = mapped_column('revrec_signature', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    revrec_signature_date: Mapped[str] = mapped_column('revrec_signature_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    revrec_implicit_flag: Mapped[str] = mapped_column('revrec_implicit_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    bypass_sch_flag: Mapped[str] = mapped_column('bypass_sch_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pre_exploded_flag: Mapped[str] = mapped_column('pre_exploded_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    inst_id: Mapped[str] = mapped_column('inst_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_line_value: Mapped[str] = mapped_column('tax_line_value', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_bill_profile_id: Mapped[str] = mapped_column('service_bill_profile_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_cov_template_id: Mapped[str] = mapped_column('service_cov_template_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_subs_template_id: Mapped[str] = mapped_column('service_subs_template_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_bill_option_code: Mapped[str] = mapped_column('service_bill_option_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_first_period_amount: Mapped[str] = mapped_column('service_first_period_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_first_period_enddate: Mapped[str] = mapped_column('service_first_period_enddate', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    subscription_enable_flag: Mapped[str] = mapped_column('subscription_enable_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    fulfillment_base: Mapped[str] = mapped_column('fulfillment_base', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    container_number: Mapped[str] = mapped_column('container_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    equipment_id: Mapped[str] = mapped_column('equipment_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    require_billing_validation: Mapped[str] = mapped_column('require_billing_validation', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    billing_plan_header_id: Mapped[str] = mapped_column('billing_plan_header_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    source_order_line_id: Mapped[str] = mapped_column('source_order_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    vrm_last_update_date: Mapped[str] = mapped_column('vrm_last_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})

        

    

    OrgOrganizationDefinitions_organization_id: Mapped["OrgOrganizationDefinitions"] = relationship(back_populates="OeOrderLinesAll_ship_from_org_id", primaryjoin="OrgOrganizationDefinitions.organization_id==OeOrderLinesAll.ship_from_org_id", foreign_keys="[OrgOrganizationDefinitions.organization_id]", viewonly=True)
        

    

    MtlSystemItemsB_organization_id: Mapped["MtlSystemItemsB"] = relationship(back_populates="OeOrderLinesAll_ship_from_org_id", primaryjoin="MtlSystemItemsB.organization_id==OeOrderLinesAll.ship_from_org_id", foreign_keys="[MtlSystemItemsB.organization_id]", viewonly=True)
        

    

    MtlSystemItemsB_inventory_item_id: Mapped["MtlSystemItemsB"] = relationship(back_populates="OeOrderLinesAll_inventory_item_id", primaryjoin="MtlSystemItemsB.inventory_item_id==OeOrderLinesAll.inventory_item_id", foreign_keys="[MtlSystemItemsB.inventory_item_id]", viewonly=True)
        

    

    WshDeliveryDetails_source_line_id: Mapped["WshDeliveryDetails"] = relationship(back_populates="OeOrderLinesAll_line_id", primaryjoin="WshDeliveryDetails.source_line_id==OeOrderLinesAll.line_id", foreign_keys="[OeOrderLinesAll.line_id]", viewonly=True)
        

    

    OeOrderHeadersAll_header_id: Mapped["OeOrderHeadersAll"] = relationship(back_populates="OeOrderLinesAll_header_id", primaryjoin="OeOrderHeadersAll.header_id==OeOrderLinesAll.header_id", foreign_keys="[OeOrderLinesAll.header_id]", viewonly=True)



