from typing import TYPE_CHECKING

from sqlalchemy import Date, Float, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from efficieno.components.erd_objects import ERDBase, ColumnMetadata

if TYPE_CHECKING:
    from ..po.po_lines_all import PoLinesAll


class PoHeadersAll(ERDBase):
    __data_object_type__ = "data_object"
    __tablename__ = "po_headers_all"
    __table_args__ = {"schema": "po", "extend_existing": True}
    __table_properties__ = {"ui_x_pos": 432.5823516845703, "ui_y_pos": 1338.5424499511719, "colour": "#F2F3F5"}

    po_header_id: Mapped[str] = mapped_column('po_header_id', Integer, primary_key=True, info={"column_metadata": ColumnMetadata()})
    agent_id: Mapped[str] = mapped_column('agent_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    type_lookup_code: Mapped[str] = mapped_column('type_lookup_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_update_date: Mapped[str] = mapped_column('last_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_updated_by: Mapped[str] = mapped_column('last_updated_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    segment1: Mapped[str] = mapped_column('segment1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    summary_flag: Mapped[str] = mapped_column('summary_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    enabled_flag: Mapped[str] = mapped_column('enabled_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    segment2: Mapped[str] = mapped_column('segment2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    segment3: Mapped[str] = mapped_column('segment3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    segment4: Mapped[str] = mapped_column('segment4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    segment5: Mapped[str] = mapped_column('segment5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    start_date_active: Mapped[str] = mapped_column('start_date_active', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    end_date_active: Mapped[str] = mapped_column('end_date_active', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_update_login: Mapped[str] = mapped_column('last_update_login', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    creation_date: Mapped[str] = mapped_column('creation_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    created_by: Mapped[str] = mapped_column('created_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    vendor_id: Mapped[str] = mapped_column('vendor_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    vendor_site_id: Mapped[str] = mapped_column('vendor_site_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    vendor_contact_id: Mapped[str] = mapped_column('vendor_contact_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_to_location_id: Mapped[str] = mapped_column('ship_to_location_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    bill_to_location_id: Mapped[str] = mapped_column('bill_to_location_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    terms_id: Mapped[str] = mapped_column('terms_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_via_lookup_code: Mapped[str] = mapped_column('ship_via_lookup_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    fob_lookup_code: Mapped[str] = mapped_column('fob_lookup_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    freight_terms_lookup_code: Mapped[str] = mapped_column('freight_terms_lookup_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    status_lookup_code: Mapped[str] = mapped_column('status_lookup_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    currency_code: Mapped[str] = mapped_column('currency_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    rate_type: Mapped[str] = mapped_column('rate_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    rate_date: Mapped[str] = mapped_column('rate_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    rate: Mapped[str] = mapped_column('rate', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    from_header_id: Mapped[str] = mapped_column('from_header_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    from_type_lookup_code: Mapped[str] = mapped_column('from_type_lookup_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    start_date: Mapped[str] = mapped_column('start_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    end_date: Mapped[str] = mapped_column('end_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    blanket_total_amount: Mapped[str] = mapped_column('blanket_total_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    authorization_status: Mapped[str] = mapped_column('authorization_status', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    revision_num: Mapped[str] = mapped_column('revision_num', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    revised_date: Mapped[str] = mapped_column('revised_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    approved_flag: Mapped[str] = mapped_column('approved_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    approved_date: Mapped[str] = mapped_column('approved_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amount_limit: Mapped[str] = mapped_column('amount_limit', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    min_release_amount: Mapped[str] = mapped_column('min_release_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    note_to_authorizer: Mapped[str] = mapped_column('note_to_authorizer', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    note_to_vendor: Mapped[str] = mapped_column('note_to_vendor', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    note_to_receiver: Mapped[str] = mapped_column('note_to_receiver', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    print_count: Mapped[str] = mapped_column('print_count', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    printed_date: Mapped[str] = mapped_column('printed_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    vendor_order_num: Mapped[str] = mapped_column('vendor_order_num', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    confirming_order_flag: Mapped[str] = mapped_column('confirming_order_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    comments: Mapped[str] = mapped_column('comments', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    reply_date: Mapped[str] = mapped_column('reply_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    reply_method_lookup_code: Mapped[str] = mapped_column('reply_method_lookup_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    rfq_close_date: Mapped[str] = mapped_column('rfq_close_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    quote_type_lookup_code: Mapped[str] = mapped_column('quote_type_lookup_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    quotation_class_code: Mapped[str] = mapped_column('quotation_class_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    quote_warning_delay_unit: Mapped[str] = mapped_column('quote_warning_delay_unit', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    quote_warning_delay: Mapped[str] = mapped_column('quote_warning_delay', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    quote_vendor_quote_number: Mapped[str] = mapped_column('quote_vendor_quote_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    acceptance_required_flag: Mapped[str] = mapped_column('acceptance_required_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    acceptance_due_date: Mapped[str] = mapped_column('acceptance_due_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    closed_date: Mapped[str] = mapped_column('closed_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    user_hold_flag: Mapped[str] = mapped_column('user_hold_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    approval_required_flag: Mapped[str] = mapped_column('approval_required_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cancel_flag: Mapped[str] = mapped_column('cancel_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    firm_status_lookup_code: Mapped[str] = mapped_column('firm_status_lookup_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    firm_date: Mapped[str] = mapped_column('firm_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    frozen_flag: Mapped[str] = mapped_column('frozen_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute_category: Mapped[str] = mapped_column('attribute_category', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute1: Mapped[str] = mapped_column('attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute2: Mapped[str] = mapped_column('attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute3: Mapped[str] = mapped_column('attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute4: Mapped[str] = mapped_column('attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute5: Mapped[str] = mapped_column('attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute6: Mapped[str] = mapped_column('attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute7: Mapped[str] = mapped_column('attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute8: Mapped[str] = mapped_column('attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute9: Mapped[str] = mapped_column('attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute10: Mapped[str] = mapped_column('attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute11: Mapped[str] = mapped_column('attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute12: Mapped[str] = mapped_column('attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute13: Mapped[str] = mapped_column('attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute14: Mapped[str] = mapped_column('attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute15: Mapped[str] = mapped_column('attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    closed_code: Mapped[str] = mapped_column('closed_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ussgl_transaction_code: Mapped[str] = mapped_column('ussgl_transaction_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    government_context: Mapped[str] = mapped_column('government_context', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    request_id: Mapped[str] = mapped_column('request_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_application_id: Mapped[str] = mapped_column('program_application_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_id: Mapped[str] = mapped_column('program_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_update_date: Mapped[str] = mapped_column('program_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    org_id: Mapped[str] = mapped_column('org_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    supply_agreement_flag: Mapped[str] = mapped_column('supply_agreement_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    edi_processed_flag: Mapped[str] = mapped_column('edi_processed_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    edi_processed_status: Mapped[str] = mapped_column('edi_processed_status', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute_category: Mapped[str] = mapped_column('global_attribute_category', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute1: Mapped[str] = mapped_column('global_attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute2: Mapped[str] = mapped_column('global_attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute3: Mapped[str] = mapped_column('global_attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute4: Mapped[str] = mapped_column('global_attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute5: Mapped[str] = mapped_column('global_attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute6: Mapped[str] = mapped_column('global_attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute7: Mapped[str] = mapped_column('global_attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute8: Mapped[str] = mapped_column('global_attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute9: Mapped[str] = mapped_column('global_attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute10: Mapped[str] = mapped_column('global_attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute11: Mapped[str] = mapped_column('global_attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute12: Mapped[str] = mapped_column('global_attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute13: Mapped[str] = mapped_column('global_attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute14: Mapped[str] = mapped_column('global_attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute15: Mapped[str] = mapped_column('global_attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute16: Mapped[str] = mapped_column('global_attribute16', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute17: Mapped[str] = mapped_column('global_attribute17', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute18: Mapped[str] = mapped_column('global_attribute18', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute19: Mapped[str] = mapped_column('global_attribute19', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute20: Mapped[str] = mapped_column('global_attribute20', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_source_code: Mapped[str] = mapped_column('interface_source_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    reference_num: Mapped[str] = mapped_column('reference_num', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    wf_item_type: Mapped[str] = mapped_column('wf_item_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    wf_item_key: Mapped[str] = mapped_column('wf_item_key', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    mrc_rate_type: Mapped[str] = mapped_column('mrc_rate_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    mrc_rate_date: Mapped[str] = mapped_column('mrc_rate_date', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    mrc_rate: Mapped[str] = mapped_column('mrc_rate', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pcard_id: Mapped[str] = mapped_column('pcard_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    price_update_tolerance: Mapped[str] = mapped_column('price_update_tolerance', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pay_on_code: Mapped[str] = mapped_column('pay_on_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    xml_flag: Mapped[str] = mapped_column('xml_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    xml_send_date: Mapped[str] = mapped_column('xml_send_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    xml_change_send_date: Mapped[str] = mapped_column('xml_change_send_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_agreement_flag: Mapped[str] = mapped_column('global_agreement_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    consigned_consumption_flag: Mapped[str] = mapped_column('consigned_consumption_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cbc_accounting_date: Mapped[str] = mapped_column('cbc_accounting_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    consume_req_demand_flag: Mapped[str] = mapped_column('consume_req_demand_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    change_requested_by: Mapped[str] = mapped_column('change_requested_by', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shipping_control: Mapped[str] = mapped_column('shipping_control', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    conterms_exist_flag: Mapped[str] = mapped_column('conterms_exist_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    conterms_articles_upd_date: Mapped[str] = mapped_column('conterms_articles_upd_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    conterms_deliv_upd_date: Mapped[str] = mapped_column('conterms_deliv_upd_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    encumbrance_required: Mapped[str] = mapped_column('encumbrance_required', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pending_signature_flag: Mapped[str] = mapped_column('pending_signature_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    change_summary: Mapped[str] = mapped_column('change_summary', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    encumbrance_required_flag: Mapped[str] = mapped_column('encumbrance_required_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    document_creation_method: Mapped[str] = mapped_column('document_creation_method', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    submit_date: Mapped[str] = mapped_column('submit_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    supplier_notif_method: Mapped[str] = mapped_column('supplier_notif_method', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    fax: Mapped[str] = mapped_column('fax', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    email_address: Mapped[str] = mapped_column('email_address', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    retro_price_comm_updates_flag: Mapped[str] = mapped_column('retro_price_comm_updates_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    retro_price_apply_updates_flag: Mapped[str] = mapped_column('retro_price_apply_updates_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    update_sourcing_rules_flag: Mapped[str] = mapped_column('update_sourcing_rules_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    auto_sourcing_flag: Mapped[str] = mapped_column('auto_sourcing_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    created_language: Mapped[str] = mapped_column('created_language', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cpa_reference: Mapped[str] = mapped_column('cpa_reference', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    lock_owner_role: Mapped[str] = mapped_column('lock_owner_role', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    lock_owner_user_id: Mapped[str] = mapped_column('lock_owner_user_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    supplier_auth_enabled_flag: Mapped[str] = mapped_column('supplier_auth_enabled_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cat_admin_auth_enabled_flag: Mapped[str] = mapped_column('cat_admin_auth_enabled_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    style_id: Mapped[str] = mapped_column('style_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_attribute_update_code: Mapped[str] = mapped_column('tax_attribute_update_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_updated_program: Mapped[str] = mapped_column('last_updated_program', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    enable_all_sites: Mapped[str] = mapped_column('enable_all_sites', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pay_when_paid: Mapped[str] = mapped_column('pay_when_paid', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    comm_rev_num: Mapped[str] = mapped_column('comm_rev_num', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_document_number: Mapped[str] = mapped_column('clm_document_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    otm_status_code: Mapped[str] = mapped_column('otm_status_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    otm_recovery_flag: Mapped[str] = mapped_column('otm_recovery_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    uda_template_id: Mapped[str] = mapped_column('uda_template_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    uda_template_date: Mapped[str] = mapped_column('uda_template_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    user_document_status: Mapped[str] = mapped_column('user_document_status', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ame_approval_id: Mapped[str] = mapped_column('ame_approval_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    draft_id: Mapped[str] = mapped_column('draft_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_effective_date: Mapped[str] = mapped_column('clm_effective_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_vendor_offer_number: Mapped[str] = mapped_column('clm_vendor_offer_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_award_administrator: Mapped[str] = mapped_column('clm_award_administrator', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_no_signed_copies_to_return: Mapped[str] = mapped_column('clm_no_signed_copies_to_return', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_min_guarantee_award_amt: Mapped[str] = mapped_column('clm_min_guarantee_award_amt', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_min_guar_award_amt_percent: Mapped[str] = mapped_column('clm_min_guar_award_amt_percent', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_min_order_amount: Mapped[str] = mapped_column('clm_min_order_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_max_order_amount: Mapped[str] = mapped_column('clm_max_order_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_amt_synced_to_agreement: Mapped[str] = mapped_column('clm_amt_synced_to_agreement', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_amount_released: Mapped[str] = mapped_column('clm_amount_released', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_external_idv: Mapped[str] = mapped_column('clm_external_idv', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_supplier_name: Mapped[str] = mapped_column('clm_supplier_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_supplier_site_name: Mapped[str] = mapped_column('clm_supplier_site_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_source_document_id: Mapped[str] = mapped_column('clm_source_document_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_issuing_office: Mapped[str] = mapped_column('clm_issuing_office', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_cotr_office: Mapped[str] = mapped_column('clm_cotr_office', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_cotr_contact: Mapped[str] = mapped_column('clm_cotr_contact', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_priority_code: Mapped[str] = mapped_column('clm_priority_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_mod_issuing_office: Mapped[str] = mapped_column('clm_mod_issuing_office', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_standard_form: Mapped[str] = mapped_column('clm_standard_form', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_document_format: Mapped[str] = mapped_column('clm_document_format', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ame_transaction_type: Mapped[str] = mapped_column('ame_transaction_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_award_type: Mapped[str] = mapped_column('clm_award_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_contract_officer: Mapped[str] = mapped_column('clm_contract_officer', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_closeout_status: Mapped[str] = mapped_column('clm_closeout_status', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    umbrella_program_id: Mapped[str] = mapped_column('umbrella_program_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    fon_ref_id: Mapped[str] = mapped_column('fon_ref_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_default_dist_flag: Mapped[str] = mapped_column('clm_default_dist_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_edagen_date: Mapped[str] = mapped_column('clm_edagen_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_contract_finance_code: Mapped[str] = mapped_column('clm_contract_finance_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_payment_instr_code: Mapped[str] = mapped_column('clm_payment_instr_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_special_contract_type: Mapped[str] = mapped_column('clm_special_contract_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    igt_document_number: Mapped[str] = mapped_column('igt_document_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    igt_gtnc_number: Mapped[str] = mapped_column('igt_gtnc_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    igt_status: Mapped[str] = mapped_column('igt_status', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    agreement_type: Mapped[str] = mapped_column('agreement_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    assisted_acquisition_ind: Mapped[str] = mapped_column('assisted_acquisition_ind', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    advance_payment_ind: Mapped[str] = mapped_column('advance_payment_ind', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    enforce_total_amt_ind: Mapped[str] = mapped_column('enforce_total_amt_ind', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    termination_days: Mapped[str] = mapped_column('termination_days', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    total_remaining_amt: Mapped[str] = mapped_column('total_remaining_amt', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    igt_business_txn_id: Mapped[str] = mapped_column('igt_business_txn_id', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    order_originating_ind: Mapped[str] = mapped_column('order_originating_ind', String, primary_key=False, info={"column_metadata": ColumnMetadata()})

        

    

    PoLinesAll_po_header_id: Mapped["PoLinesAll"] = relationship(back_populates="PoHeadersAll_po_header_id", primaryjoin="PoLinesAll.po_header_id==PoHeadersAll.po_header_id", foreign_keys="[PoLinesAll.po_header_id]", viewonly=True)



