from typing import TYPE_CHECKING

from sqlalchemy import Date, Float, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from efficieno.components.erd_objects import ERDBase, ColumnMetadata

if TYPE_CHECKING:
    from ..po.po_distributions_all import PoDistributionsAll
    from ..po.po_headers_all import PoHeadersAll


class PoLinesAll(ERDBase):
    __data_object_type__ = "data_object"
    __tablename__ = "po_lines_all"
    __table_args__ = {"schema": "po", "extend_existing": True}
    __table_properties__ = {"ui_x_pos": 156.53761291503906, "ui_y_pos": 1493.0640258789062, "colour": "#F2F3F5"}

    po_line_id: Mapped[str] = mapped_column('po_line_id', Integer, primary_key=True, info={"column_metadata": ColumnMetadata()})
    last_update_date: Mapped[str] = mapped_column('last_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_updated_by: Mapped[str] = mapped_column('last_updated_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    po_header_id: Mapped[str] = mapped_column('po_header_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    line_type_id: Mapped[str] = mapped_column('line_type_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    line_num: Mapped[str] = mapped_column('line_num', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_update_login: Mapped[str] = mapped_column('last_update_login', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    creation_date: Mapped[str] = mapped_column('creation_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    created_by: Mapped[str] = mapped_column('created_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    item_id: Mapped[str] = mapped_column('item_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    item_revision: Mapped[str] = mapped_column('item_revision', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    category_id: Mapped[str] = mapped_column('category_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    item_description: Mapped[str] = mapped_column('item_description', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    unit_meas_lookup_code: Mapped[str] = mapped_column('unit_meas_lookup_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    quantity_committed: Mapped[str] = mapped_column('quantity_committed', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    committed_amount: Mapped[str] = mapped_column('committed_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    allow_price_override_flag: Mapped[str] = mapped_column('allow_price_override_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    not_to_exceed_price: Mapped[str] = mapped_column('not_to_exceed_price', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    list_price_per_unit: Mapped[str] = mapped_column('list_price_per_unit', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    unit_price: Mapped[str] = mapped_column('unit_price', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    quantity: Mapped[str] = mapped_column('quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    un_number_id: Mapped[str] = mapped_column('un_number_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    hazard_class_id: Mapped[str] = mapped_column('hazard_class_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    note_to_vendor: Mapped[str] = mapped_column('note_to_vendor', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    from_header_id: Mapped[str] = mapped_column('from_header_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    from_line_id: Mapped[str] = mapped_column('from_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    min_order_quantity: Mapped[str] = mapped_column('min_order_quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    max_order_quantity: Mapped[str] = mapped_column('max_order_quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    qty_rcv_tolerance: Mapped[str] = mapped_column('qty_rcv_tolerance', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    over_tolerance_error_flag: Mapped[str] = mapped_column('over_tolerance_error_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    market_price: Mapped[str] = mapped_column('market_price', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    unordered_flag: Mapped[str] = mapped_column('unordered_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    closed_flag: Mapped[str] = mapped_column('closed_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    user_hold_flag: Mapped[str] = mapped_column('user_hold_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cancel_flag: Mapped[str] = mapped_column('cancel_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cancelled_by: Mapped[str] = mapped_column('cancelled_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cancel_date: Mapped[str] = mapped_column('cancel_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    firm_status_lookup_code: Mapped[str] = mapped_column('firm_status_lookup_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    firm_date: Mapped[str] = mapped_column('firm_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    vendor_product_num: Mapped[str] = mapped_column('vendor_product_num', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    contract_num: Mapped[str] = mapped_column('contract_num', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    taxable_flag: Mapped[str] = mapped_column('taxable_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_name: Mapped[str] = mapped_column('tax_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    type_1099: Mapped[str] = mapped_column('type_1099', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    capital_expense_flag: Mapped[str] = mapped_column('capital_expense_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    negotiated_by_preparer_flag: Mapped[str] = mapped_column('negotiated_by_preparer_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute_category: Mapped[str] = mapped_column('attribute_category', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute1: Mapped[str] = mapped_column('attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute2: Mapped[str] = mapped_column('attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute3: Mapped[str] = mapped_column('attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute4: Mapped[str] = mapped_column('attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute5: Mapped[str] = mapped_column('attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute6: Mapped[str] = mapped_column('attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute7: Mapped[str] = mapped_column('attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute8: Mapped[str] = mapped_column('attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute9: Mapped[str] = mapped_column('attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute10: Mapped[str] = mapped_column('attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    reference_num: Mapped[str] = mapped_column('reference_num', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute11: Mapped[str] = mapped_column('attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute12: Mapped[str] = mapped_column('attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute13: Mapped[str] = mapped_column('attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute14: Mapped[str] = mapped_column('attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute15: Mapped[str] = mapped_column('attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    min_release_amount: Mapped[str] = mapped_column('min_release_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    price_type_lookup_code: Mapped[str] = mapped_column('price_type_lookup_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    closed_code: Mapped[str] = mapped_column('closed_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    price_break_lookup_code: Mapped[str] = mapped_column('price_break_lookup_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ussgl_transaction_code: Mapped[str] = mapped_column('ussgl_transaction_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    government_context: Mapped[str] = mapped_column('government_context', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    request_id: Mapped[str] = mapped_column('request_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_application_id: Mapped[str] = mapped_column('program_application_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_id: Mapped[str] = mapped_column('program_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_update_date: Mapped[str] = mapped_column('program_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    closed_date: Mapped[str] = mapped_column('closed_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    closed_by: Mapped[str] = mapped_column('closed_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    transaction_reason_code: Mapped[str] = mapped_column('transaction_reason_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    org_id: Mapped[str] = mapped_column('org_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    qc_grade: Mapped[str] = mapped_column('qc_grade', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    base_uom: Mapped[str] = mapped_column('base_uom', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    base_qty: Mapped[str] = mapped_column('base_qty', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    secondary_uom: Mapped[str] = mapped_column('secondary_uom', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    secondary_qty: Mapped[str] = mapped_column('secondary_qty', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute_category: Mapped[str] = mapped_column('global_attribute_category', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute1: Mapped[str] = mapped_column('global_attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute2: Mapped[str] = mapped_column('global_attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute3: Mapped[str] = mapped_column('global_attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute4: Mapped[str] = mapped_column('global_attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute5: Mapped[str] = mapped_column('global_attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute6: Mapped[str] = mapped_column('global_attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute7: Mapped[str] = mapped_column('global_attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute8: Mapped[str] = mapped_column('global_attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute9: Mapped[str] = mapped_column('global_attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute10: Mapped[str] = mapped_column('global_attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute11: Mapped[str] = mapped_column('global_attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute12: Mapped[str] = mapped_column('global_attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute13: Mapped[str] = mapped_column('global_attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute14: Mapped[str] = mapped_column('global_attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute15: Mapped[str] = mapped_column('global_attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute16: Mapped[str] = mapped_column('global_attribute16', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute17: Mapped[str] = mapped_column('global_attribute17', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute18: Mapped[str] = mapped_column('global_attribute18', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute19: Mapped[str] = mapped_column('global_attribute19', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute20: Mapped[str] = mapped_column('global_attribute20', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    line_reference_num: Mapped[str] = mapped_column('line_reference_num', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    project_id: Mapped[str] = mapped_column('project_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    task_id: Mapped[str] = mapped_column('task_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    expiration_date: Mapped[str] = mapped_column('expiration_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_code_id: Mapped[str] = mapped_column('tax_code_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    oke_contract_header_id: Mapped[str] = mapped_column('oke_contract_header_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    oke_contract_version_id: Mapped[str] = mapped_column('oke_contract_version_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    secondary_quantity: Mapped[str] = mapped_column('secondary_quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    secondary_unit_of_measure: Mapped[str] = mapped_column('secondary_unit_of_measure', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    preferred_grade: Mapped[str] = mapped_column('preferred_grade', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    auction_header_id: Mapped[str] = mapped_column('auction_header_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    auction_display_number: Mapped[str] = mapped_column('auction_display_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    auction_line_number: Mapped[str] = mapped_column('auction_line_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    bid_number: Mapped[str] = mapped_column('bid_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    bid_line_number: Mapped[str] = mapped_column('bid_line_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    retroactive_date: Mapped[str] = mapped_column('retroactive_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    supplier_ref_number: Mapped[str] = mapped_column('supplier_ref_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    contract_id: Mapped[str] = mapped_column('contract_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    start_date: Mapped[str] = mapped_column('start_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amount: Mapped[str] = mapped_column('amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    job_id: Mapped[str] = mapped_column('job_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    contractor_first_name: Mapped[str] = mapped_column('contractor_first_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    contractor_last_name: Mapped[str] = mapped_column('contractor_last_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    from_line_location_id: Mapped[str] = mapped_column('from_line_location_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    order_type_lookup_code: Mapped[str] = mapped_column('order_type_lookup_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    purchase_basis: Mapped[str] = mapped_column('purchase_basis', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    matching_basis: Mapped[str] = mapped_column('matching_basis', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    svc_amount_notif_sent: Mapped[str] = mapped_column('svc_amount_notif_sent', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    svc_completion_notif_sent: Mapped[str] = mapped_column('svc_completion_notif_sent', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    base_unit_price: Mapped[str] = mapped_column('base_unit_price', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    manual_price_change_flag: Mapped[str] = mapped_column('manual_price_change_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    retainage_rate: Mapped[str] = mapped_column('retainage_rate', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    max_retainage_amount: Mapped[str] = mapped_column('max_retainage_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    progress_payment_rate: Mapped[str] = mapped_column('progress_payment_rate', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    recoupment_rate: Mapped[str] = mapped_column('recoupment_rate', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    catalog_name: Mapped[str] = mapped_column('catalog_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    supplier_part_auxid: Mapped[str] = mapped_column('supplier_part_auxid', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ip_category_id: Mapped[str] = mapped_column('ip_category_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_attribute_update_code: Mapped[str] = mapped_column('tax_attribute_update_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_updated_program: Mapped[str] = mapped_column('last_updated_program', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    group_line_id: Mapped[str] = mapped_column('group_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    line_num_display: Mapped[str] = mapped_column('line_num_display', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_info_flag: Mapped[str] = mapped_column('clm_info_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_option_indicator: Mapped[str] = mapped_column('clm_option_indicator', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_base_line_num: Mapped[str] = mapped_column('clm_base_line_num', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_option_num: Mapped[str] = mapped_column('clm_option_num', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_option_from_date: Mapped[str] = mapped_column('clm_option_from_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_option_to_date: Mapped[str] = mapped_column('clm_option_to_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_funded_flag: Mapped[str] = mapped_column('clm_funded_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    contract_type: Mapped[str] = mapped_column('contract_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cost_constraint: Mapped[str] = mapped_column('cost_constraint', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_idc_type: Mapped[str] = mapped_column('clm_idc_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    uda_template_id: Mapped[str] = mapped_column('uda_template_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    user_document_status: Mapped[str] = mapped_column('user_document_status', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    draft_id: Mapped[str] = mapped_column('draft_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_exercised_flag: Mapped[str] = mapped_column('clm_exercised_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_exercised_date: Mapped[str] = mapped_column('clm_exercised_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_min_total_amount: Mapped[str] = mapped_column('clm_min_total_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_max_total_amount: Mapped[str] = mapped_column('clm_max_total_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_min_total_quantity: Mapped[str] = mapped_column('clm_min_total_quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_max_total_quantity: Mapped[str] = mapped_column('clm_max_total_quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_min_order_amount: Mapped[str] = mapped_column('clm_min_order_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_max_order_amount: Mapped[str] = mapped_column('clm_max_order_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_min_order_quantity: Mapped[str] = mapped_column('clm_min_order_quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_max_order_quantity: Mapped[str] = mapped_column('clm_max_order_quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_total_amount_ordered: Mapped[str] = mapped_column('clm_total_amount_ordered', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_total_quantity_ordered: Mapped[str] = mapped_column('clm_total_quantity_ordered', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_fsc_psc: Mapped[str] = mapped_column('clm_fsc_psc', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_mdaps_mais: Mapped[str] = mapped_column('clm_mdaps_mais', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_naics: Mapped[str] = mapped_column('clm_naics', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_order_start_date: Mapped[str] = mapped_column('clm_order_start_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_order_end_date: Mapped[str] = mapped_column('clm_order_end_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    revision_num: Mapped[str] = mapped_column('revision_num', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_approved_undef_amount: Mapped[str] = mapped_column('clm_approved_undef_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_delivery_event_code: Mapped[str] = mapped_column('clm_delivery_event_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_exhibit_name: Mapped[str] = mapped_column('clm_exhibit_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_payment_instr_code: Mapped[str] = mapped_column('clm_payment_instr_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_pop_exception_reason: Mapped[str] = mapped_column('clm_pop_exception_reason', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_uda_pricing_total: Mapped[str] = mapped_column('clm_uda_pricing_total', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_undef_action_code: Mapped[str] = mapped_column('clm_undef_action_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_undef_flag: Mapped[str] = mapped_column('clm_undef_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    schedules_required_flag: Mapped[str] = mapped_column('schedules_required_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    igt_line_status: Mapped[str] = mapped_column('igt_line_status', String, primary_key=False, info={"column_metadata": ColumnMetadata()})

        

    

    PoDistributionsAll_po_line_id: Mapped["PoDistributionsAll"] = relationship(back_populates="PoLinesAll_po_line_id", primaryjoin="PoDistributionsAll.po_line_id==PoLinesAll.po_line_id", foreign_keys="[PoDistributionsAll.po_line_id]", viewonly=True)
        

    

    PoHeadersAll_po_header_id: Mapped["PoHeadersAll"] = relationship(back_populates="PoLinesAll_po_header_id", primaryjoin="PoHeadersAll.po_header_id==PoLinesAll.po_header_id", foreign_keys="[PoLinesAll.po_header_id]", viewonly=True)



