from typing import TYPE_CHECKING

from sqlalchemy import Date, Float, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from efficieno.components.erd_objects import ERDBase, ColumnMetadata

if TYPE_CHECKING:
    from ..po.po_req_distributions_all import PoReqDistributionsAll
    from ..po.po_requisition_headers_all import PoRequisitionHeadersAll


class PoRequisitionLinesAll(ERDBase):
    __data_object_type__ = "data_object"
    __tablename__ = "po_requisition_lines_all"
    __table_args__ = {"schema": "po", "extend_existing": True}
    __table_properties__ = {"ui_x_pos": -118.17846369743347, "ui_y_pos": 1361.7463073730469, "colour": "#F2F3F5"}

    requisition_line_id: Mapped[str] = mapped_column('requisition_line_id', Integer, primary_key=True, info={"column_metadata": ColumnMetadata()})
    requisition_header_id: Mapped[str] = mapped_column('requisition_header_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    line_num: Mapped[str] = mapped_column('line_num', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    line_type_id: Mapped[str] = mapped_column('line_type_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    category_id: Mapped[str] = mapped_column('category_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    item_description: Mapped[str] = mapped_column('item_description', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    unit_meas_lookup_code: Mapped[str] = mapped_column('unit_meas_lookup_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    unit_price: Mapped[str] = mapped_column('unit_price', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    quantity: Mapped[str] = mapped_column('quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    deliver_to_location_id: Mapped[str] = mapped_column('deliver_to_location_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    to_person_id: Mapped[str] = mapped_column('to_person_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_update_date: Mapped[str] = mapped_column('last_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_updated_by: Mapped[str] = mapped_column('last_updated_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    source_type_code: Mapped[str] = mapped_column('source_type_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_update_login: Mapped[str] = mapped_column('last_update_login', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    creation_date: Mapped[str] = mapped_column('creation_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    created_by: Mapped[str] = mapped_column('created_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    item_id: Mapped[str] = mapped_column('item_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    item_revision: Mapped[str] = mapped_column('item_revision', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    quantity_delivered: Mapped[str] = mapped_column('quantity_delivered', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    suggested_buyer_id: Mapped[str] = mapped_column('suggested_buyer_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    encumbered_flag: Mapped[str] = mapped_column('encumbered_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    rfq_required_flag: Mapped[str] = mapped_column('rfq_required_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    need_by_date: Mapped[str] = mapped_column('need_by_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    line_location_id: Mapped[str] = mapped_column('line_location_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    modified_by_agent_flag: Mapped[str] = mapped_column('modified_by_agent_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    parent_req_line_id: Mapped[str] = mapped_column('parent_req_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    justification: Mapped[str] = mapped_column('justification', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    note_to_agent: Mapped[str] = mapped_column('note_to_agent', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    note_to_receiver: Mapped[str] = mapped_column('note_to_receiver', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    purchasing_agent_id: Mapped[str] = mapped_column('purchasing_agent_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    document_type_code: Mapped[str] = mapped_column('document_type_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    blanket_po_header_id: Mapped[str] = mapped_column('blanket_po_header_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    blanket_po_line_num: Mapped[str] = mapped_column('blanket_po_line_num', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    currency_code: Mapped[str] = mapped_column('currency_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    rate_type: Mapped[str] = mapped_column('rate_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    rate_date: Mapped[str] = mapped_column('rate_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    rate: Mapped[str] = mapped_column('rate', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    currency_unit_price: Mapped[str] = mapped_column('currency_unit_price', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    suggested_vendor_name: Mapped[str] = mapped_column('suggested_vendor_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    suggested_vendor_location: Mapped[str] = mapped_column('suggested_vendor_location', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    suggested_vendor_product_code: Mapped[str] = mapped_column('suggested_vendor_product_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    un_number_id: Mapped[str] = mapped_column('un_number_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    hazard_class_id: Mapped[str] = mapped_column('hazard_class_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    must_use_sugg_vendor_flag: Mapped[str] = mapped_column('must_use_sugg_vendor_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    reference_num: Mapped[str] = mapped_column('reference_num', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    on_rfq_flag: Mapped[str] = mapped_column('on_rfq_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    urgent_flag: Mapped[str] = mapped_column('urgent_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cancel_flag: Mapped[str] = mapped_column('cancel_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    source_organization_id: Mapped[str] = mapped_column('source_organization_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    source_subinventory: Mapped[str] = mapped_column('source_subinventory', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    destination_type_code: Mapped[str] = mapped_column('destination_type_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    destination_organization_id: Mapped[str] = mapped_column('destination_organization_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    destination_subinventory: Mapped[str] = mapped_column('destination_subinventory', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    quantity_cancelled: Mapped[str] = mapped_column('quantity_cancelled', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cancel_date: Mapped[str] = mapped_column('cancel_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cancel_reason: Mapped[str] = mapped_column('cancel_reason', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    closed_code: Mapped[str] = mapped_column('closed_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    agent_return_note: Mapped[str] = mapped_column('agent_return_note', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    changed_after_research_flag: Mapped[str] = mapped_column('changed_after_research_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    vendor_id: Mapped[str] = mapped_column('vendor_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    vendor_site_id: Mapped[str] = mapped_column('vendor_site_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    vendor_contact_id: Mapped[str] = mapped_column('vendor_contact_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    research_agent_id: Mapped[str] = mapped_column('research_agent_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    on_line_flag: Mapped[str] = mapped_column('on_line_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    wip_entity_id: Mapped[str] = mapped_column('wip_entity_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    wip_line_id: Mapped[str] = mapped_column('wip_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    wip_repetitive_schedule_id: Mapped[str] = mapped_column('wip_repetitive_schedule_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    wip_operation_seq_num: Mapped[str] = mapped_column('wip_operation_seq_num', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    wip_resource_seq_num: Mapped[str] = mapped_column('wip_resource_seq_num', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute_category: Mapped[str] = mapped_column('attribute_category', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    destination_context: Mapped[str] = mapped_column('destination_context', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    inventory_source_context: Mapped[str] = mapped_column('inventory_source_context', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    vendor_source_context: Mapped[str] = mapped_column('vendor_source_context', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute1: Mapped[str] = mapped_column('attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute2: Mapped[str] = mapped_column('attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute3: Mapped[str] = mapped_column('attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute4: Mapped[str] = mapped_column('attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute5: Mapped[str] = mapped_column('attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute6: Mapped[str] = mapped_column('attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute7: Mapped[str] = mapped_column('attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute8: Mapped[str] = mapped_column('attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute9: Mapped[str] = mapped_column('attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute10: Mapped[str] = mapped_column('attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute11: Mapped[str] = mapped_column('attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute12: Mapped[str] = mapped_column('attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute13: Mapped[str] = mapped_column('attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute14: Mapped[str] = mapped_column('attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute15: Mapped[str] = mapped_column('attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    bom_resource_id: Mapped[str] = mapped_column('bom_resource_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    request_id: Mapped[str] = mapped_column('request_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_application_id: Mapped[str] = mapped_column('program_application_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_id: Mapped[str] = mapped_column('program_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_update_date: Mapped[str] = mapped_column('program_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ussgl_transaction_code: Mapped[str] = mapped_column('ussgl_transaction_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    government_context: Mapped[str] = mapped_column('government_context', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    closed_date: Mapped[str] = mapped_column('closed_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    transaction_reason_code: Mapped[str] = mapped_column('transaction_reason_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    quantity_received: Mapped[str] = mapped_column('quantity_received', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    source_req_line_id: Mapped[str] = mapped_column('source_req_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    org_id: Mapped[str] = mapped_column('org_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute1: Mapped[str] = mapped_column('global_attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute2: Mapped[str] = mapped_column('global_attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute3: Mapped[str] = mapped_column('global_attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute4: Mapped[str] = mapped_column('global_attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute5: Mapped[str] = mapped_column('global_attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute6: Mapped[str] = mapped_column('global_attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute7: Mapped[str] = mapped_column('global_attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute8: Mapped[str] = mapped_column('global_attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute9: Mapped[str] = mapped_column('global_attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute10: Mapped[str] = mapped_column('global_attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute11: Mapped[str] = mapped_column('global_attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute12: Mapped[str] = mapped_column('global_attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute13: Mapped[str] = mapped_column('global_attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute14: Mapped[str] = mapped_column('global_attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute15: Mapped[str] = mapped_column('global_attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute16: Mapped[str] = mapped_column('global_attribute16', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute17: Mapped[str] = mapped_column('global_attribute17', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute18: Mapped[str] = mapped_column('global_attribute18', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute19: Mapped[str] = mapped_column('global_attribute19', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute20: Mapped[str] = mapped_column('global_attribute20', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute_category: Mapped[str] = mapped_column('global_attribute_category', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    kanban_card_id: Mapped[str] = mapped_column('kanban_card_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    catalog_type: Mapped[str] = mapped_column('catalog_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    catalog_source: Mapped[str] = mapped_column('catalog_source', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    manufacturer_id: Mapped[str] = mapped_column('manufacturer_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    manufacturer_name: Mapped[str] = mapped_column('manufacturer_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    manufacturer_part_number: Mapped[str] = mapped_column('manufacturer_part_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    requester_email: Mapped[str] = mapped_column('requester_email', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    requester_fax: Mapped[str] = mapped_column('requester_fax', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    requester_phone: Mapped[str] = mapped_column('requester_phone', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    unspsc_code: Mapped[str] = mapped_column('unspsc_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    other_category_code: Mapped[str] = mapped_column('other_category_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    supplier_duns: Mapped[str] = mapped_column('supplier_duns', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_status_indicator: Mapped[str] = mapped_column('tax_status_indicator', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pcard_flag: Mapped[str] = mapped_column('pcard_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    new_supplier_flag: Mapped[str] = mapped_column('new_supplier_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    auto_receive_flag: Mapped[str] = mapped_column('auto_receive_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_user_override_flag: Mapped[str] = mapped_column('tax_user_override_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_code_id: Mapped[str] = mapped_column('tax_code_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    note_to_vendor: Mapped[str] = mapped_column('note_to_vendor', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    oke_contract_version_id: Mapped[str] = mapped_column('oke_contract_version_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    oke_contract_header_id: Mapped[str] = mapped_column('oke_contract_header_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    item_source_id: Mapped[str] = mapped_column('item_source_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    supplier_ref_number: Mapped[str] = mapped_column('supplier_ref_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    secondary_unit_of_measure: Mapped[str] = mapped_column('secondary_unit_of_measure', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    secondary_quantity: Mapped[str] = mapped_column('secondary_quantity', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    preferred_grade: Mapped[str] = mapped_column('preferred_grade', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    secondary_quantity_received: Mapped[str] = mapped_column('secondary_quantity_received', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    secondary_quantity_cancelled: Mapped[str] = mapped_column('secondary_quantity_cancelled', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    vmi_flag: Mapped[str] = mapped_column('vmi_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    auction_header_id: Mapped[str] = mapped_column('auction_header_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    auction_display_number: Mapped[str] = mapped_column('auction_display_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    auction_line_number: Mapped[str] = mapped_column('auction_line_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    reqs_in_pool_flag: Mapped[str] = mapped_column('reqs_in_pool_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    bid_number: Mapped[str] = mapped_column('bid_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    bid_line_number: Mapped[str] = mapped_column('bid_line_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    noncat_template_id: Mapped[str] = mapped_column('noncat_template_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    suggested_vendor_contact_email: Mapped[str] = mapped_column('suggested_vendor_contact_email', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amount: Mapped[str] = mapped_column('amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    currency_amount: Mapped[str] = mapped_column('currency_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    labor_req_line_id: Mapped[str] = mapped_column('labor_req_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    job_id: Mapped[str] = mapped_column('job_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    job_long_description: Mapped[str] = mapped_column('job_long_description', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    contractor_status: Mapped[str] = mapped_column('contractor_status', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    contact_information: Mapped[str] = mapped_column('contact_information', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    suggested_supplier_flag: Mapped[str] = mapped_column('suggested_supplier_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    candidate_screening_reqd_flag: Mapped[str] = mapped_column('candidate_screening_reqd_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    candidate_full_name: Mapped[str] = mapped_column('candidate_full_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    assignment_end_date: Mapped[str] = mapped_column('assignment_end_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    overtime_allowed_flag: Mapped[str] = mapped_column('overtime_allowed_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    contractor_requisition_flag: Mapped[str] = mapped_column('contractor_requisition_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    drop_ship_flag: Mapped[str] = mapped_column('drop_ship_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    candidate_first_name: Mapped[str] = mapped_column('candidate_first_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    candidate_last_name: Mapped[str] = mapped_column('candidate_last_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    assignment_start_date: Mapped[str] = mapped_column('assignment_start_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    order_type_lookup_code: Mapped[str] = mapped_column('order_type_lookup_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    purchase_basis: Mapped[str] = mapped_column('purchase_basis', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    matching_basis: Mapped[str] = mapped_column('matching_basis', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    negotiated_by_preparer_flag: Mapped[str] = mapped_column('negotiated_by_preparer_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_method: Mapped[str] = mapped_column('ship_method', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    estimated_pickup_date: Mapped[str] = mapped_column('estimated_pickup_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    supplier_notified_for_cancel: Mapped[str] = mapped_column('supplier_notified_for_cancel', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    base_unit_price: Mapped[str] = mapped_column('base_unit_price', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    at_sourcing_flag: Mapped[str] = mapped_column('at_sourcing_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_attribute_update_code: Mapped[str] = mapped_column('tax_attribute_update_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_name: Mapped[str] = mapped_column('tax_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    transferred_to_oe_flag: Mapped[str] = mapped_column('transferred_to_oe_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    conformed_line_id: Mapped[str] = mapped_column('conformed_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amendment_type: Mapped[str] = mapped_column('amendment_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amendment_status: Mapped[str] = mapped_column('amendment_status', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    line_num_display: Mapped[str] = mapped_column('line_num_display', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    group_line_id: Mapped[str] = mapped_column('group_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_info_flag: Mapped[str] = mapped_column('clm_info_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_option_indicator: Mapped[str] = mapped_column('clm_option_indicator', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_base_line_num: Mapped[str] = mapped_column('clm_base_line_num', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_option_num: Mapped[str] = mapped_column('clm_option_num', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_option_from_date: Mapped[str] = mapped_column('clm_option_from_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_option_to_date: Mapped[str] = mapped_column('clm_option_to_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_funded_flag: Mapped[str] = mapped_column('clm_funded_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    uda_template_id: Mapped[str] = mapped_column('uda_template_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    contract_type: Mapped[str] = mapped_column('contract_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cost_constraint: Mapped[str] = mapped_column('cost_constraint', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amendment_response_reason: Mapped[str] = mapped_column('amendment_response_reason', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_period_perf_start_date: Mapped[str] = mapped_column('clm_period_perf_start_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_period_perf_end_date: Mapped[str] = mapped_column('clm_period_perf_end_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_extended_item_description: Mapped[str] = mapped_column('clm_extended_item_description', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_option_exercised: Mapped[str] = mapped_column('clm_option_exercised', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    is_line_num_display_modified: Mapped[str] = mapped_column('is_line_num_display_modified', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    assignment_number: Mapped[str] = mapped_column('assignment_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    po_draft_id: Mapped[str] = mapped_column('po_draft_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    po_line_id: Mapped[str] = mapped_column('po_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_exercised_date: Mapped[str] = mapped_column('clm_exercised_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    linked_to_fund: Mapped[str] = mapped_column('linked_to_fund', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    fund_source_not_known: Mapped[str] = mapped_column('fund_source_not_known', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    linked_po_count: Mapped[str] = mapped_column('linked_po_count', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clm_mipr_obligation_type: Mapped[str] = mapped_column('clm_mipr_obligation_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    par_draft_id: Mapped[str] = mapped_column('par_draft_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    par_line_id: Mapped[str] = mapped_column('par_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    req_template_name: Mapped[str] = mapped_column('req_template_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    req_template_line_num: Mapped[str] = mapped_column('req_template_line_num', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    punchout_item_id: Mapped[str] = mapped_column('punchout_item_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    spot_buy_flag: Mapped[str] = mapped_column('spot_buy_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    buyer_assistance_required: Mapped[str] = mapped_column('buyer_assistance_required', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    suggest_multiple_suppliers: Mapped[str] = mapped_column('suggest_multiple_suppliers', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    createspotbuyflag: Mapped[str] = mapped_column('createspotbuyflag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    newsupp_registration_id: Mapped[str] = mapped_column('newsupp_registration_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_src_line_id: Mapped[str] = mapped_column('interface_src_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})

        

    

    PoReqDistributionsAll_requisition_line_id: Mapped["PoReqDistributionsAll"] = relationship(back_populates="PoRequisitionLinesAll_requisition_line_id", primaryjoin="PoReqDistributionsAll.requisition_line_id==PoRequisitionLinesAll.requisition_line_id", foreign_keys="[PoReqDistributionsAll.requisition_line_id]", viewonly=True)
        

    

    PoRequisitionHeadersAll_requisition_header_id: Mapped["PoRequisitionHeadersAll"] = relationship(back_populates="PoRequisitionLinesAll_requisition_header_id", primaryjoin="PoRequisitionHeadersAll.requisition_header_id==PoRequisitionLinesAll.requisition_header_id", foreign_keys="[PoRequisitionLinesAll.requisition_header_id]", viewonly=True)



