from typing import TYPE_CHECKING

from sqlalchemy import Date, Float, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from efficieno.components.erd_objects import ERDBase, ColumnMetadata

if TYPE_CHECKING:
    from ..ont.oe_order_headers_all import OeOrderHeadersAll
    from ..wsh.wsh_delivery_assignments import WshDeliveryAssignments


class WshNewDeliveries(ERDBase):
    __data_object_type__ = "data_object"
    __tablename__ = "wsh_new_deliveries"
    __table_args__ = {"schema": "wsh", "extend_existing": True}
    __table_properties__ = {"ui_x_pos": 1735.416015625, "ui_y_pos": 470.982421875, "colour": "#F2F3F5"}

    delivery_id: Mapped[str] = mapped_column('delivery_id', Integer, primary_key=True, info={"column_metadata": ColumnMetadata()})
    name: Mapped[str] = mapped_column('name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    planned_flag: Mapped[str] = mapped_column('planned_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    status_code: Mapped[str] = mapped_column('status_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    initial_pickup_date: Mapped[str] = mapped_column('initial_pickup_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    initial_pickup_location_id: Mapped[str] = mapped_column('initial_pickup_location_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ultimate_dropoff_location_id: Mapped[str] = mapped_column('ultimate_dropoff_location_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ultimate_dropoff_date: Mapped[str] = mapped_column('ultimate_dropoff_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    customer_id: Mapped[str] = mapped_column('customer_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    intmed_ship_to_location_id: Mapped[str] = mapped_column('intmed_ship_to_location_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pooled_ship_to_location_id: Mapped[str] = mapped_column('pooled_ship_to_location_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    freight_terms_code: Mapped[str] = mapped_column('freight_terms_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    fob_code: Mapped[str] = mapped_column('fob_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    fob_location_id: Mapped[str] = mapped_column('fob_location_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    waybill: Mapped[str] = mapped_column('waybill', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    acceptance_flag: Mapped[str] = mapped_column('acceptance_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    accepted_by: Mapped[str] = mapped_column('accepted_by', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    accepted_date: Mapped[str] = mapped_column('accepted_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    acknowledged_by: Mapped[str] = mapped_column('acknowledged_by', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    confirmed_by: Mapped[str] = mapped_column('confirmed_by', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    asn_date_sent: Mapped[str] = mapped_column('asn_date_sent', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    asn_status_code: Mapped[str] = mapped_column('asn_status_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    asn_seq_number: Mapped[str] = mapped_column('asn_seq_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    reason_of_transport: Mapped[str] = mapped_column('reason_of_transport', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    description: Mapped[str] = mapped_column('description', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    gross_weight: Mapped[str] = mapped_column('gross_weight', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    net_weight: Mapped[str] = mapped_column('net_weight', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    weight_uom_code: Mapped[str] = mapped_column('weight_uom_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    volume: Mapped[str] = mapped_column('volume', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    volume_uom_code: Mapped[str] = mapped_column('volume_uom_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    additional_shipment_info: Mapped[str] = mapped_column('additional_shipment_info', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    port_of_discharge: Mapped[str] = mapped_column('port_of_discharge', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    booking_number: Mapped[str] = mapped_column('booking_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cod_amount: Mapped[str] = mapped_column('cod_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cod_currency_code: Mapped[str] = mapped_column('cod_currency_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_contract: Mapped[str] = mapped_column('service_contract', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cod_remit_to: Mapped[str] = mapped_column('cod_remit_to', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cod_charge_paid_by: Mapped[str] = mapped_column('cod_charge_paid_by', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    problem_contact_reference: Mapped[str] = mapped_column('problem_contact_reference', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    bill_freight_to: Mapped[str] = mapped_column('bill_freight_to', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    carried_by: Mapped[str] = mapped_column('carried_by', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    port_of_loading: Mapped[str] = mapped_column('port_of_loading', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute_category: Mapped[str] = mapped_column('attribute_category', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute1: Mapped[str] = mapped_column('attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute2: Mapped[str] = mapped_column('attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute3: Mapped[str] = mapped_column('attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute4: Mapped[str] = mapped_column('attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute5: Mapped[str] = mapped_column('attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute6: Mapped[str] = mapped_column('attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute7: Mapped[str] = mapped_column('attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute8: Mapped[str] = mapped_column('attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute9: Mapped[str] = mapped_column('attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute10: Mapped[str] = mapped_column('attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute11: Mapped[str] = mapped_column('attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute12: Mapped[str] = mapped_column('attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute13: Mapped[str] = mapped_column('attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute14: Mapped[str] = mapped_column('attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute15: Mapped[str] = mapped_column('attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute_category: Mapped[str] = mapped_column('tp_attribute_category', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute1: Mapped[str] = mapped_column('tp_attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute2: Mapped[str] = mapped_column('tp_attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute3: Mapped[str] = mapped_column('tp_attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute4: Mapped[str] = mapped_column('tp_attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute5: Mapped[str] = mapped_column('tp_attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute6: Mapped[str] = mapped_column('tp_attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute7: Mapped[str] = mapped_column('tp_attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute8: Mapped[str] = mapped_column('tp_attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute9: Mapped[str] = mapped_column('tp_attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute10: Mapped[str] = mapped_column('tp_attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute11: Mapped[str] = mapped_column('tp_attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute12: Mapped[str] = mapped_column('tp_attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute13: Mapped[str] = mapped_column('tp_attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute14: Mapped[str] = mapped_column('tp_attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_attribute15: Mapped[str] = mapped_column('tp_attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    creation_date: Mapped[str] = mapped_column('creation_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    created_by: Mapped[str] = mapped_column('created_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_update_date: Mapped[str] = mapped_column('last_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_updated_by: Mapped[str] = mapped_column('last_updated_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_update_login: Mapped[str] = mapped_column('last_update_login', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_application_id: Mapped[str] = mapped_column('program_application_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_id: Mapped[str] = mapped_column('program_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_update_date: Mapped[str] = mapped_column('program_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    request_id: Mapped[str] = mapped_column('request_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute_category: Mapped[str] = mapped_column('global_attribute_category', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute1: Mapped[str] = mapped_column('global_attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute2: Mapped[str] = mapped_column('global_attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute3: Mapped[str] = mapped_column('global_attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute4: Mapped[str] = mapped_column('global_attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute5: Mapped[str] = mapped_column('global_attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute6: Mapped[str] = mapped_column('global_attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute7: Mapped[str] = mapped_column('global_attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute8: Mapped[str] = mapped_column('global_attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute9: Mapped[str] = mapped_column('global_attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute10: Mapped[str] = mapped_column('global_attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute11: Mapped[str] = mapped_column('global_attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute12: Mapped[str] = mapped_column('global_attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute13: Mapped[str] = mapped_column('global_attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute14: Mapped[str] = mapped_column('global_attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute15: Mapped[str] = mapped_column('global_attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute16: Mapped[str] = mapped_column('global_attribute16', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute17: Mapped[str] = mapped_column('global_attribute17', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute18: Mapped[str] = mapped_column('global_attribute18', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute19: Mapped[str] = mapped_column('global_attribute19', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute20: Mapped[str] = mapped_column('global_attribute20', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    confirm_date: Mapped[str] = mapped_column('confirm_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_method_code: Mapped[str] = mapped_column('ship_method_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    dock_code: Mapped[str] = mapped_column('dock_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    delivery_type: Mapped[str] = mapped_column('delivery_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    carrier_id: Mapped[str] = mapped_column('carrier_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    currency_code: Mapped[str] = mapped_column('currency_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    organization_id: Mapped[str] = mapped_column('organization_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    loading_sequence: Mapped[str] = mapped_column('loading_sequence', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    loading_order_flag: Mapped[str] = mapped_column('loading_order_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    number_of_lpn: Mapped[str] = mapped_column('number_of_lpn', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    batch_id: Mapped[str] = mapped_column('batch_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    source_header_id: Mapped[str] = mapped_column('source_header_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    hash_value: Mapped[str] = mapped_column('hash_value', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ftz_number: Mapped[str] = mapped_column('ftz_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    routed_export_txn: Mapped[str] = mapped_column('routed_export_txn', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    entry_number: Mapped[str] = mapped_column('entry_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    routing_instructions: Mapped[str] = mapped_column('routing_instructions', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    in_bond_code: Mapped[str] = mapped_column('in_bond_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shipping_marks: Mapped[str] = mapped_column('shipping_marks', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_level: Mapped[str] = mapped_column('service_level', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    mode_of_transport: Mapped[str] = mapped_column('mode_of_transport', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    assigned_to_fte_trips: Mapped[str] = mapped_column('assigned_to_fte_trips', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    auto_sc_exclude_flag: Mapped[str] = mapped_column('auto_sc_exclude_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    auto_ap_exclude_flag: Mapped[str] = mapped_column('auto_ap_exclude_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ap_batch_id: Mapped[str] = mapped_column('ap_batch_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_delivery_number: Mapped[str] = mapped_column('tp_delivery_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tp_plan_name: Mapped[str] = mapped_column('tp_plan_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    vendor_id: Mapped[str] = mapped_column('vendor_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    earliest_pickup_date: Mapped[str] = mapped_column('earliest_pickup_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    latest_pickup_date: Mapped[str] = mapped_column('latest_pickup_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    earliest_dropoff_date: Mapped[str] = mapped_column('earliest_dropoff_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    latest_dropoff_date: Mapped[str] = mapped_column('latest_dropoff_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ignore_for_planning: Mapped[str] = mapped_column('ignore_for_planning', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    party_id: Mapped[str] = mapped_column('party_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    routing_response_id: Mapped[str] = mapped_column('routing_response_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    rcv_shipment_header_id: Mapped[str] = mapped_column('rcv_shipment_header_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    asn_shipment_header_id: Mapped[str] = mapped_column('asn_shipment_header_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shipment_direction: Mapped[str] = mapped_column('shipment_direction', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shipping_control: Mapped[str] = mapped_column('shipping_control', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    wv_frozen_flag: Mapped[str] = mapped_column('wv_frozen_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    itinerary_complete: Mapped[str] = mapped_column('itinerary_complete', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    delivered_date: Mapped[str] = mapped_column('delivered_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    delivery_wf_process: Mapped[str] = mapped_column('delivery_wf_process', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    del_wf_intransit_attr: Mapped[str] = mapped_column('del_wf_intransit_attr', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    del_wf_interface_attr: Mapped[str] = mapped_column('del_wf_interface_attr', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    del_wf_close_attr: Mapped[str] = mapped_column('del_wf_close_attr', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    delivery_scpod_wf_process: Mapped[str] = mapped_column('delivery_scpod_wf_process', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tms_version_number: Mapped[str] = mapped_column('tms_version_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tms_interface_flag: Mapped[str] = mapped_column('tms_interface_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    pending_advice_flag: Mapped[str] = mapped_column('pending_advice_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    client_id: Mapped[str] = mapped_column('client_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    consignee_flag: Mapped[str] = mapped_column('consignee_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    service_org_id: Mapped[str] = mapped_column('service_org_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tms_sub_batch_id: Mapped[str] = mapped_column('tms_sub_batch_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    source_header_type_id: Mapped[str] = mapped_column('source_header_type_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_set_id: Mapped[str] = mapped_column('ship_set_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shipment_priority_code: Mapped[str] = mapped_column('shipment_priority_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    group_attribute1: Mapped[str] = mapped_column('group_attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    group_attribute2: Mapped[str] = mapped_column('group_attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    group_attribute3: Mapped[str] = mapped_column('group_attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    group_attribute4: Mapped[str] = mapped_column('group_attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    group_attribute5: Mapped[str] = mapped_column('group_attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    group_attribute6: Mapped[str] = mapped_column('group_attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    group_attribute7: Mapped[str] = mapped_column('group_attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    group_attribute8: Mapped[str] = mapped_column('group_attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    group_attribute9: Mapped[str] = mapped_column('group_attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    group_attribute10: Mapped[str] = mapped_column('group_attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    group_attribute11: Mapped[str] = mapped_column('group_attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    group_attribute12: Mapped[str] = mapped_column('group_attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    group_attribute13: Mapped[str] = mapped_column('group_attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    group_attribute14: Mapped[str] = mapped_column('group_attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    group_attribute15: Mapped[str] = mapped_column('group_attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})

        

    

    OeOrderHeadersAll_header_id: Mapped["OeOrderHeadersAll"] = relationship(back_populates="WshNewDeliveries_source_header_id", primaryjoin="OeOrderHeadersAll.header_id==WshNewDeliveries.source_header_id", foreign_keys="[OeOrderHeadersAll.header_id]", viewonly=True)
        

    

    WshDeliveryAssignments_delivery_id: Mapped["WshDeliveryAssignments"] = relationship(back_populates="WshNewDeliveries_delivery_id", primaryjoin="WshDeliveryAssignments.delivery_id==WshNewDeliveries.delivery_id", foreign_keys="[WshDeliveryAssignments.delivery_id]", viewonly=True)



