from typing import TYPE_CHECKING

from sqlalchemy import Date, Float, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from efficieno.components.erd_objects import ERDBase, ColumnMetadata

if TYPE_CHECKING:
    from ..ar.hz_party_sites import HzPartySites


class HzLocations(ERDBase):
    __data_object_type__ = "data_object"
    __tablename__ = "hz_locations"
    __table_args__ = {"schema": "ar", "extend_existing": True}
    __table_properties__ = {"ui_x_pos": 1715.4207763671875, "ui_y_pos": 1464.8385620117188, "colour": "#F2F3F5"}

    location_id: Mapped[str] = mapped_column('location_id', Integer, primary_key=True, info={"column_metadata": ColumnMetadata()})
    last_update_date: Mapped[str] = mapped_column('last_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_updated_by: Mapped[str] = mapped_column('last_updated_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    creation_date: Mapped[str] = mapped_column('creation_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    created_by: Mapped[str] = mapped_column('created_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_update_login: Mapped[str] = mapped_column('last_update_login', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    request_id: Mapped[str] = mapped_column('request_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_application_id: Mapped[str] = mapped_column('program_application_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_id: Mapped[str] = mapped_column('program_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_update_date: Mapped[str] = mapped_column('program_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    wh_update_date: Mapped[str] = mapped_column('wh_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute_category: Mapped[str] = mapped_column('attribute_category', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute1: Mapped[str] = mapped_column('attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute2: Mapped[str] = mapped_column('attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute3: Mapped[str] = mapped_column('attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute4: Mapped[str] = mapped_column('attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute5: Mapped[str] = mapped_column('attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute6: Mapped[str] = mapped_column('attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute7: Mapped[str] = mapped_column('attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute8: Mapped[str] = mapped_column('attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute9: Mapped[str] = mapped_column('attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute10: Mapped[str] = mapped_column('attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute11: Mapped[str] = mapped_column('attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute12: Mapped[str] = mapped_column('attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute13: Mapped[str] = mapped_column('attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute14: Mapped[str] = mapped_column('attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute15: Mapped[str] = mapped_column('attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute16: Mapped[str] = mapped_column('attribute16', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute17: Mapped[str] = mapped_column('attribute17', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute18: Mapped[str] = mapped_column('attribute18', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute19: Mapped[str] = mapped_column('attribute19', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute20: Mapped[str] = mapped_column('attribute20', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute_category: Mapped[str] = mapped_column('global_attribute_category', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute1: Mapped[str] = mapped_column('global_attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute2: Mapped[str] = mapped_column('global_attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute3: Mapped[str] = mapped_column('global_attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute4: Mapped[str] = mapped_column('global_attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute5: Mapped[str] = mapped_column('global_attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute6: Mapped[str] = mapped_column('global_attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute7: Mapped[str] = mapped_column('global_attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute8: Mapped[str] = mapped_column('global_attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute9: Mapped[str] = mapped_column('global_attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute10: Mapped[str] = mapped_column('global_attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute11: Mapped[str] = mapped_column('global_attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute12: Mapped[str] = mapped_column('global_attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute13: Mapped[str] = mapped_column('global_attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute14: Mapped[str] = mapped_column('global_attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute15: Mapped[str] = mapped_column('global_attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute16: Mapped[str] = mapped_column('global_attribute16', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute17: Mapped[str] = mapped_column('global_attribute17', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute18: Mapped[str] = mapped_column('global_attribute18', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute19: Mapped[str] = mapped_column('global_attribute19', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute20: Mapped[str] = mapped_column('global_attribute20', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    orig_system_reference: Mapped[str] = mapped_column('orig_system_reference', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    country: Mapped[str] = mapped_column('country', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    address1: Mapped[str] = mapped_column('address1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    address2: Mapped[str] = mapped_column('address2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    address3: Mapped[str] = mapped_column('address3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    address4: Mapped[str] = mapped_column('address4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    city: Mapped[str] = mapped_column('city', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    postal_code: Mapped[str] = mapped_column('postal_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    state: Mapped[str] = mapped_column('state', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    province: Mapped[str] = mapped_column('province', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    county: Mapped[str] = mapped_column('county', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    address_key: Mapped[str] = mapped_column('address_key', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    address_style: Mapped[str] = mapped_column('address_style', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    validated_flag: Mapped[str] = mapped_column('validated_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    address_lines_phonetic: Mapped[str] = mapped_column('address_lines_phonetic', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    apartment_flag: Mapped[str] = mapped_column('apartment_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    po_box_number: Mapped[str] = mapped_column('po_box_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    house_number: Mapped[str] = mapped_column('house_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    street_suffix: Mapped[str] = mapped_column('street_suffix', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    apartment_number: Mapped[str] = mapped_column('apartment_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    secondary_suffix_element: Mapped[str] = mapped_column('secondary_suffix_element', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    street: Mapped[str] = mapped_column('street', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    rural_route_type: Mapped[str] = mapped_column('rural_route_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    rural_route_number: Mapped[str] = mapped_column('rural_route_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    street_number: Mapped[str] = mapped_column('street_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    building: Mapped[str] = mapped_column('building', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    floor: Mapped[str] = mapped_column('floor', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    suite: Mapped[str] = mapped_column('suite', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    room: Mapped[str] = mapped_column('room', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    postal_plus4_code: Mapped[str] = mapped_column('postal_plus4_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    time_zone: Mapped[str] = mapped_column('time_zone', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    overseas_address_flag: Mapped[str] = mapped_column('overseas_address_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    post_office: Mapped[str] = mapped_column('post_office', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    position: Mapped[str] = mapped_column('position', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    delivery_point_code: Mapped[str] = mapped_column('delivery_point_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    location_directions: Mapped[str] = mapped_column('location_directions', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    address_effective_date: Mapped[str] = mapped_column('address_effective_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    address_expiration_date: Mapped[str] = mapped_column('address_expiration_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    address_error_code: Mapped[str] = mapped_column('address_error_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    clli_code: Mapped[str] = mapped_column('clli_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    dodaac: Mapped[str] = mapped_column('dodaac', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    trailing_directory_code: Mapped[str] = mapped_column('trailing_directory_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    language: Mapped[str] = mapped_column('language', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    life_cycle_status: Mapped[str] = mapped_column('life_cycle_status', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    short_description: Mapped[str] = mapped_column('short_description', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    description: Mapped[str] = mapped_column('description', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    content_source_type: Mapped[str] = mapped_column('content_source_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    loc_hierarchy_id: Mapped[str] = mapped_column('loc_hierarchy_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    sales_tax_geocode: Mapped[str] = mapped_column('sales_tax_geocode', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    sales_tax_inside_city_limits: Mapped[str] = mapped_column('sales_tax_inside_city_limits', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    fa_location_id: Mapped[str] = mapped_column('fa_location_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    geometry: Mapped[str] = mapped_column('geometry', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    object_version_number: Mapped[str] = mapped_column('object_version_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    created_by_module: Mapped[str] = mapped_column('created_by_module', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    application_id: Mapped[str] = mapped_column('application_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    timezone_id: Mapped[str] = mapped_column('timezone_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    geometry_status_code: Mapped[str] = mapped_column('geometry_status_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    actual_content_source: Mapped[str] = mapped_column('actual_content_source', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    validation_status_code: Mapped[str] = mapped_column('validation_status_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    date_validated: Mapped[str] = mapped_column('date_validated', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    do_not_validate_flag: Mapped[str] = mapped_column('do_not_validate_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    geometry_source: Mapped[str] = mapped_column('geometry_source', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    geometry_accuracy: Mapped[str] = mapped_column('geometry_accuracy', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})

        

    

    HzPartySites_location_id: Mapped["HzPartySites"] = relationship(back_populates="HzLocations_location_id", primaryjoin="HzPartySites.location_id==HzLocations.location_id", foreign_keys="[HzLocations.location_id]", viewonly=True)



