from typing import TYPE_CHECKING

from sqlalchemy import Date, Float, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from efficieno.components.erd_objects import ERDBase, ColumnMetadata

if TYPE_CHECKING:
    from ..ar.ra_cust_trx_types_all import RaCustTrxTypesAll
    from ..ar.ra_terms_tl import RaTermsTl
    from ..ar.ra_customer_trx_lines_all import RaCustomerTrxLinesAll


class RaCustomerTrxAll(ERDBase):
    __data_object_type__ = "data_object"
    __tablename__ = "ra_customer_trx_all"
    __table_args__ = {"schema": "ar", "extend_existing": True}
    __table_properties__ = {"ui_x_pos": 1751.4593505859375, "ui_y_pos": 949.06884765625, "colour": "#F2F3F5"}

    customer_trx_id: Mapped[str] = mapped_column('customer_trx_id', Integer, primary_key=True, info={"column_metadata": ColumnMetadata()})
    last_update_date: Mapped[str] = mapped_column('last_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_updated_by: Mapped[str] = mapped_column('last_updated_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    creation_date: Mapped[str] = mapped_column('creation_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    created_by: Mapped[str] = mapped_column('created_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_update_login: Mapped[str] = mapped_column('last_update_login', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    trx_number: Mapped[str] = mapped_column('trx_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cust_trx_type_id: Mapped[str] = mapped_column('cust_trx_type_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    trx_date: Mapped[str] = mapped_column('trx_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    set_of_books_id: Mapped[str] = mapped_column('set_of_books_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    bill_to_contact_id: Mapped[str] = mapped_column('bill_to_contact_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    batch_id: Mapped[str] = mapped_column('batch_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    batch_source_id: Mapped[str] = mapped_column('batch_source_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    reason_code: Mapped[str] = mapped_column('reason_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    sold_to_customer_id: Mapped[str] = mapped_column('sold_to_customer_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    sold_to_contact_id: Mapped[str] = mapped_column('sold_to_contact_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    sold_to_site_use_id: Mapped[str] = mapped_column('sold_to_site_use_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    bill_to_customer_id: Mapped[str] = mapped_column('bill_to_customer_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    bill_to_site_use_id: Mapped[str] = mapped_column('bill_to_site_use_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_to_customer_id: Mapped[str] = mapped_column('ship_to_customer_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_to_contact_id: Mapped[str] = mapped_column('ship_to_contact_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_to_site_use_id: Mapped[str] = mapped_column('ship_to_site_use_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    shipment_id: Mapped[str] = mapped_column('shipment_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    remit_to_address_id: Mapped[str] = mapped_column('remit_to_address_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    term_id: Mapped[str] = mapped_column('term_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    term_due_date: Mapped[str] = mapped_column('term_due_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    previous_customer_trx_id: Mapped[str] = mapped_column('previous_customer_trx_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    primary_salesrep_id: Mapped[str] = mapped_column('primary_salesrep_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    printing_original_date: Mapped[str] = mapped_column('printing_original_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    printing_last_printed: Mapped[str] = mapped_column('printing_last_printed', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    printing_option: Mapped[str] = mapped_column('printing_option', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    printing_count: Mapped[str] = mapped_column('printing_count', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    printing_pending: Mapped[str] = mapped_column('printing_pending', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    purchase_order: Mapped[str] = mapped_column('purchase_order', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    purchase_order_revision: Mapped[str] = mapped_column('purchase_order_revision', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    purchase_order_date: Mapped[str] = mapped_column('purchase_order_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    customer_reference: Mapped[str] = mapped_column('customer_reference', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    customer_reference_date: Mapped[str] = mapped_column('customer_reference_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    comments: Mapped[str] = mapped_column('comments', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    internal_notes: Mapped[str] = mapped_column('internal_notes', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    exchange_rate_type: Mapped[str] = mapped_column('exchange_rate_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    exchange_date: Mapped[str] = mapped_column('exchange_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    exchange_rate: Mapped[str] = mapped_column('exchange_rate', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    territory_id: Mapped[str] = mapped_column('territory_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    invoice_currency_code: Mapped[str] = mapped_column('invoice_currency_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    initial_customer_trx_id: Mapped[str] = mapped_column('initial_customer_trx_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    agreement_id: Mapped[str] = mapped_column('agreement_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    end_date_commitment: Mapped[str] = mapped_column('end_date_commitment', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    start_date_commitment: Mapped[str] = mapped_column('start_date_commitment', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_printed_sequence_num: Mapped[str] = mapped_column('last_printed_sequence_num', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute_category: Mapped[str] = mapped_column('attribute_category', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute1: Mapped[str] = mapped_column('attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute2: Mapped[str] = mapped_column('attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute3: Mapped[str] = mapped_column('attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute4: Mapped[str] = mapped_column('attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute5: Mapped[str] = mapped_column('attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute6: Mapped[str] = mapped_column('attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute7: Mapped[str] = mapped_column('attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute8: Mapped[str] = mapped_column('attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute9: Mapped[str] = mapped_column('attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute10: Mapped[str] = mapped_column('attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    orig_system_batch_name: Mapped[str] = mapped_column('orig_system_batch_name', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    post_request_id: Mapped[str] = mapped_column('post_request_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    request_id: Mapped[str] = mapped_column('request_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_application_id: Mapped[str] = mapped_column('program_application_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_id: Mapped[str] = mapped_column('program_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_update_date: Mapped[str] = mapped_column('program_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    finance_charges: Mapped[str] = mapped_column('finance_charges', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    complete_flag: Mapped[str] = mapped_column('complete_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    posting_control_id: Mapped[str] = mapped_column('posting_control_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    bill_to_address_id: Mapped[str] = mapped_column('bill_to_address_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ra_post_loop_number: Mapped[str] = mapped_column('ra_post_loop_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_to_address_id: Mapped[str] = mapped_column('ship_to_address_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    credit_method_for_rules: Mapped[str] = mapped_column('credit_method_for_rules', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    credit_method_for_installments: Mapped[str] = mapped_column('credit_method_for_installments', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    receipt_method_id: Mapped[str] = mapped_column('receipt_method_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute11: Mapped[str] = mapped_column('attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute12: Mapped[str] = mapped_column('attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute13: Mapped[str] = mapped_column('attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute14: Mapped[str] = mapped_column('attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute15: Mapped[str] = mapped_column('attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    related_customer_trx_id: Mapped[str] = mapped_column('related_customer_trx_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    invoicing_rule_id: Mapped[str] = mapped_column('invoicing_rule_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_via: Mapped[str] = mapped_column('ship_via', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_date_actual: Mapped[str] = mapped_column('ship_date_actual', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    waybill_number: Mapped[str] = mapped_column('waybill_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    fob_point: Mapped[str] = mapped_column('fob_point', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    customer_bank_account_id: Mapped[str] = mapped_column('customer_bank_account_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_header_attribute1: Mapped[str] = mapped_column('interface_header_attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_header_attribute2: Mapped[str] = mapped_column('interface_header_attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_header_attribute3: Mapped[str] = mapped_column('interface_header_attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_header_attribute4: Mapped[str] = mapped_column('interface_header_attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_header_attribute5: Mapped[str] = mapped_column('interface_header_attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_header_attribute6: Mapped[str] = mapped_column('interface_header_attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_header_attribute7: Mapped[str] = mapped_column('interface_header_attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_header_attribute8: Mapped[str] = mapped_column('interface_header_attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_header_context: Mapped[str] = mapped_column('interface_header_context', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    default_ussgl_trx_code_context: Mapped[str] = mapped_column('default_ussgl_trx_code_context', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_header_attribute10: Mapped[str] = mapped_column('interface_header_attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_header_attribute11: Mapped[str] = mapped_column('interface_header_attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_header_attribute12: Mapped[str] = mapped_column('interface_header_attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_header_attribute13: Mapped[str] = mapped_column('interface_header_attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_header_attribute14: Mapped[str] = mapped_column('interface_header_attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_header_attribute15: Mapped[str] = mapped_column('interface_header_attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_header_attribute9: Mapped[str] = mapped_column('interface_header_attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    default_ussgl_transaction_code: Mapped[str] = mapped_column('default_ussgl_transaction_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    recurred_from_trx_number: Mapped[str] = mapped_column('recurred_from_trx_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    status_trx: Mapped[str] = mapped_column('status_trx', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    doc_sequence_id: Mapped[str] = mapped_column('doc_sequence_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    doc_sequence_value: Mapped[str] = mapped_column('doc_sequence_value', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    paying_customer_id: Mapped[str] = mapped_column('paying_customer_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    paying_site_use_id: Mapped[str] = mapped_column('paying_site_use_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    related_batch_source_id: Mapped[str] = mapped_column('related_batch_source_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    default_tax_exempt_flag: Mapped[str] = mapped_column('default_tax_exempt_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    created_from: Mapped[str] = mapped_column('created_from', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    org_id: Mapped[str] = mapped_column('org_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    wh_update_date: Mapped[str] = mapped_column('wh_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute1: Mapped[str] = mapped_column('global_attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute2: Mapped[str] = mapped_column('global_attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute3: Mapped[str] = mapped_column('global_attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute4: Mapped[str] = mapped_column('global_attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute5: Mapped[str] = mapped_column('global_attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute6: Mapped[str] = mapped_column('global_attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute7: Mapped[str] = mapped_column('global_attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute8: Mapped[str] = mapped_column('global_attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute9: Mapped[str] = mapped_column('global_attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute10: Mapped[str] = mapped_column('global_attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute11: Mapped[str] = mapped_column('global_attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute12: Mapped[str] = mapped_column('global_attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute13: Mapped[str] = mapped_column('global_attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute14: Mapped[str] = mapped_column('global_attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute15: Mapped[str] = mapped_column('global_attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute16: Mapped[str] = mapped_column('global_attribute16', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute17: Mapped[str] = mapped_column('global_attribute17', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute18: Mapped[str] = mapped_column('global_attribute18', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute19: Mapped[str] = mapped_column('global_attribute19', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute20: Mapped[str] = mapped_column('global_attribute20', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute_category: Mapped[str] = mapped_column('global_attribute_category', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    edi_processed_flag: Mapped[str] = mapped_column('edi_processed_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    edi_processed_status: Mapped[str] = mapped_column('edi_processed_status', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute21: Mapped[str] = mapped_column('global_attribute21', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute22: Mapped[str] = mapped_column('global_attribute22', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute23: Mapped[str] = mapped_column('global_attribute23', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute24: Mapped[str] = mapped_column('global_attribute24', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute25: Mapped[str] = mapped_column('global_attribute25', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute26: Mapped[str] = mapped_column('global_attribute26', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute27: Mapped[str] = mapped_column('global_attribute27', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute28: Mapped[str] = mapped_column('global_attribute28', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute29: Mapped[str] = mapped_column('global_attribute29', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute30: Mapped[str] = mapped_column('global_attribute30', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    mrc_exchange_rate_type: Mapped[str] = mapped_column('mrc_exchange_rate_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    mrc_exchange_date: Mapped[str] = mapped_column('mrc_exchange_date', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    mrc_exchange_rate: Mapped[str] = mapped_column('mrc_exchange_rate', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    payment_server_order_num: Mapped[str] = mapped_column('payment_server_order_num', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    approval_code: Mapped[str] = mapped_column('approval_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    address_verification_code: Mapped[str] = mapped_column('address_verification_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    old_trx_number: Mapped[str] = mapped_column('old_trx_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    br_amount: Mapped[str] = mapped_column('br_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    br_unpaid_flag: Mapped[str] = mapped_column('br_unpaid_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    br_on_hold_flag: Mapped[str] = mapped_column('br_on_hold_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    drawee_id: Mapped[str] = mapped_column('drawee_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    drawee_contact_id: Mapped[str] = mapped_column('drawee_contact_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    drawee_site_use_id: Mapped[str] = mapped_column('drawee_site_use_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    remittance_bank_account_id: Mapped[str] = mapped_column('remittance_bank_account_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    override_remit_account_flag: Mapped[str] = mapped_column('override_remit_account_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    drawee_bank_account_id: Mapped[str] = mapped_column('drawee_bank_account_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    special_instructions: Mapped[str] = mapped_column('special_instructions', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    remittance_batch_id: Mapped[str] = mapped_column('remittance_batch_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    prepayment_flag: Mapped[str] = mapped_column('prepayment_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ct_reference: Mapped[str] = mapped_column('ct_reference', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    contract_id: Mapped[str] = mapped_column('contract_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    bill_template_id: Mapped[str] = mapped_column('bill_template_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    reversed_cash_receipt_id: Mapped[str] = mapped_column('reversed_cash_receipt_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cc_error_code: Mapped[str] = mapped_column('cc_error_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cc_error_text: Mapped[str] = mapped_column('cc_error_text', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    cc_error_flag: Mapped[str] = mapped_column('cc_error_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    upgrade_method: Mapped[str] = mapped_column('upgrade_method', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    legal_entity_id: Mapped[str] = mapped_column('legal_entity_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    remit_bank_acct_use_id: Mapped[str] = mapped_column('remit_bank_acct_use_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    payment_trxn_extension_id: Mapped[str] = mapped_column('payment_trxn_extension_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ax_accounted_flag: Mapped[str] = mapped_column('ax_accounted_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    application_id: Mapped[str] = mapped_column('application_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    payment_attributes: Mapped[str] = mapped_column('payment_attributes', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    billing_date: Mapped[str] = mapped_column('billing_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interest_header_id: Mapped[str] = mapped_column('interest_header_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    late_charges_assessed: Mapped[str] = mapped_column('late_charges_assessed', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    trailer_number: Mapped[str] = mapped_column('trailer_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    rev_rec_application: Mapped[str] = mapped_column('rev_rec_application', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    document_type_id: Mapped[str] = mapped_column('document_type_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    document_creation_date: Mapped[str] = mapped_column('document_creation_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    src_invoicing_rule_id: Mapped[str] = mapped_column('src_invoicing_rule_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    billing_ext_request: Mapped[str] = mapped_column('billing_ext_request', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})

        

    

    RaCustTrxTypesAll_cust_trx_type_id: Mapped["RaCustTrxTypesAll"] = relationship(back_populates="RaCustomerTrxAll_cust_trx_type_id", primaryjoin="RaCustTrxTypesAll.cust_trx_type_id==RaCustomerTrxAll.cust_trx_type_id", foreign_keys="[RaCustTrxTypesAll.cust_trx_type_id]", viewonly=True)
        

    

    RaTermsTl_term_id: Mapped["RaTermsTl"] = relationship(back_populates="RaCustomerTrxAll_term_id", primaryjoin="RaTermsTl.term_id==RaCustomerTrxAll.term_id", foreign_keys="[RaTermsTl.term_id]", viewonly=True)
        

    

    RaCustomerTrxLinesAll_customer_trx_id: Mapped["RaCustomerTrxLinesAll"] = relationship(back_populates="RaCustomerTrxAll_customer_trx_id", primaryjoin="RaCustomerTrxLinesAll.customer_trx_id==RaCustomerTrxAll.customer_trx_id", foreign_keys="[RaCustomerTrxLinesAll.customer_trx_id]", viewonly=True)



