from typing import TYPE_CHECKING

from sqlalchemy import Date, Float, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from efficieno.components.erd_objects import ERDBase, ColumnMetadata

if TYPE_CHECKING:
    from ..inv.mtl_system_items_b import MtlSystemItemsB
    from ..inv.mtl_system_items_b import MtlSystemItemsB
    from ..ar.ra_customer_trx_all import RaCustomerTrxAll


class RaCustomerTrxLinesAll(ERDBase):
    __data_object_type__ = "data_object"
    __tablename__ = "ra_customer_trx_lines_all"
    __table_args__ = {"schema": "ar", "extend_existing": True}
    __table_properties__ = {"ui_x_pos": 2087.6129150390625, "ui_y_pos": 903.39208984375, "colour": "#F2F3F5"}

    customer_trx_line_id: Mapped[str] = mapped_column('customer_trx_line_id', Integer, primary_key=True, info={"column_metadata": ColumnMetadata()})
    last_update_date: Mapped[str] = mapped_column('last_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_updated_by: Mapped[str] = mapped_column('last_updated_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    creation_date: Mapped[str] = mapped_column('creation_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    created_by: Mapped[str] = mapped_column('created_by', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_update_login: Mapped[str] = mapped_column('last_update_login', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    customer_trx_id: Mapped[str] = mapped_column('customer_trx_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    line_number: Mapped[str] = mapped_column('line_number', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    set_of_books_id: Mapped[str] = mapped_column('set_of_books_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    reason_code: Mapped[str] = mapped_column('reason_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    inventory_item_id: Mapped[str] = mapped_column('inventory_item_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    description: Mapped[str] = mapped_column('description', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    previous_customer_trx_id: Mapped[str] = mapped_column('previous_customer_trx_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    previous_customer_trx_line_id: Mapped[str] = mapped_column('previous_customer_trx_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    quantity_ordered: Mapped[str] = mapped_column('quantity_ordered', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    quantity_credited: Mapped[str] = mapped_column('quantity_credited', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    quantity_invoiced: Mapped[str] = mapped_column('quantity_invoiced', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    unit_standard_price: Mapped[str] = mapped_column('unit_standard_price', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    unit_selling_price: Mapped[str] = mapped_column('unit_selling_price', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    sales_order: Mapped[str] = mapped_column('sales_order', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    sales_order_revision: Mapped[str] = mapped_column('sales_order_revision', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    sales_order_line: Mapped[str] = mapped_column('sales_order_line', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    sales_order_date: Mapped[str] = mapped_column('sales_order_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    accounting_rule_id: Mapped[str] = mapped_column('accounting_rule_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    accounting_rule_duration: Mapped[str] = mapped_column('accounting_rule_duration', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    line_type: Mapped[str] = mapped_column('line_type', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute_category: Mapped[str] = mapped_column('attribute_category', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute1: Mapped[str] = mapped_column('attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute2: Mapped[str] = mapped_column('attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute3: Mapped[str] = mapped_column('attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute4: Mapped[str] = mapped_column('attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute5: Mapped[str] = mapped_column('attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute6: Mapped[str] = mapped_column('attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute7: Mapped[str] = mapped_column('attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute8: Mapped[str] = mapped_column('attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute9: Mapped[str] = mapped_column('attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute10: Mapped[str] = mapped_column('attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    request_id: Mapped[str] = mapped_column('request_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_application_id: Mapped[str] = mapped_column('program_application_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_id: Mapped[str] = mapped_column('program_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    program_update_date: Mapped[str] = mapped_column('program_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    rule_start_date: Mapped[str] = mapped_column('rule_start_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    initial_customer_trx_line_id: Mapped[str] = mapped_column('initial_customer_trx_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_line_context: Mapped[str] = mapped_column('interface_line_context', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_line_attribute1: Mapped[str] = mapped_column('interface_line_attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_line_attribute2: Mapped[str] = mapped_column('interface_line_attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_line_attribute3: Mapped[str] = mapped_column('interface_line_attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_line_attribute4: Mapped[str] = mapped_column('interface_line_attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_line_attribute5: Mapped[str] = mapped_column('interface_line_attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_line_attribute6: Mapped[str] = mapped_column('interface_line_attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_line_attribute7: Mapped[str] = mapped_column('interface_line_attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_line_attribute8: Mapped[str] = mapped_column('interface_line_attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    sales_order_source: Mapped[str] = mapped_column('sales_order_source', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    taxable_flag: Mapped[str] = mapped_column('taxable_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    extended_amount: Mapped[str] = mapped_column('extended_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    revenue_amount: Mapped[str] = mapped_column('revenue_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    autorule_complete_flag: Mapped[str] = mapped_column('autorule_complete_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    link_to_cust_trx_line_id: Mapped[str] = mapped_column('link_to_cust_trx_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute11: Mapped[str] = mapped_column('attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute12: Mapped[str] = mapped_column('attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute13: Mapped[str] = mapped_column('attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute14: Mapped[str] = mapped_column('attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    attribute15: Mapped[str] = mapped_column('attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_precedence: Mapped[str] = mapped_column('tax_precedence', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_rate: Mapped[str] = mapped_column('tax_rate', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    item_exception_rate_id: Mapped[str] = mapped_column('item_exception_rate_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_exemption_id: Mapped[str] = mapped_column('tax_exemption_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    memo_line_id: Mapped[str] = mapped_column('memo_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    autorule_duration_processed: Mapped[str] = mapped_column('autorule_duration_processed', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    uom_code: Mapped[str] = mapped_column('uom_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    default_ussgl_transaction_code: Mapped[str] = mapped_column('default_ussgl_transaction_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    default_ussgl_trx_code_context: Mapped[str] = mapped_column('default_ussgl_trx_code_context', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_line_attribute10: Mapped[str] = mapped_column('interface_line_attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_line_attribute11: Mapped[str] = mapped_column('interface_line_attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_line_attribute12: Mapped[str] = mapped_column('interface_line_attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_line_attribute13: Mapped[str] = mapped_column('interface_line_attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_line_attribute14: Mapped[str] = mapped_column('interface_line_attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_line_attribute15: Mapped[str] = mapped_column('interface_line_attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interface_line_attribute9: Mapped[str] = mapped_column('interface_line_attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    vat_tax_id: Mapped[str] = mapped_column('vat_tax_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    autotax: Mapped[str] = mapped_column('autotax', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    last_period_to_credit: Mapped[str] = mapped_column('last_period_to_credit', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    item_context: Mapped[str] = mapped_column('item_context', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_exempt_flag: Mapped[str] = mapped_column('tax_exempt_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_exempt_number: Mapped[str] = mapped_column('tax_exempt_number', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_exempt_reason_code: Mapped[str] = mapped_column('tax_exempt_reason_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_vendor_return_code: Mapped[str] = mapped_column('tax_vendor_return_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    sales_tax_id: Mapped[str] = mapped_column('sales_tax_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    location_segment_id: Mapped[str] = mapped_column('location_segment_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    movement_id: Mapped[str] = mapped_column('movement_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    org_id: Mapped[str] = mapped_column('org_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    wh_update_date: Mapped[str] = mapped_column('wh_update_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute1: Mapped[str] = mapped_column('global_attribute1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute2: Mapped[str] = mapped_column('global_attribute2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute3: Mapped[str] = mapped_column('global_attribute3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute4: Mapped[str] = mapped_column('global_attribute4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute5: Mapped[str] = mapped_column('global_attribute5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute6: Mapped[str] = mapped_column('global_attribute6', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute7: Mapped[str] = mapped_column('global_attribute7', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute8: Mapped[str] = mapped_column('global_attribute8', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute9: Mapped[str] = mapped_column('global_attribute9', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute10: Mapped[str] = mapped_column('global_attribute10', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute11: Mapped[str] = mapped_column('global_attribute11', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute12: Mapped[str] = mapped_column('global_attribute12', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute13: Mapped[str] = mapped_column('global_attribute13', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute14: Mapped[str] = mapped_column('global_attribute14', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute15: Mapped[str] = mapped_column('global_attribute15', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute16: Mapped[str] = mapped_column('global_attribute16', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute17: Mapped[str] = mapped_column('global_attribute17', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute18: Mapped[str] = mapped_column('global_attribute18', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute19: Mapped[str] = mapped_column('global_attribute19', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute20: Mapped[str] = mapped_column('global_attribute20', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    global_attribute_category: Mapped[str] = mapped_column('global_attribute_category', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    gross_unit_selling_price: Mapped[str] = mapped_column('gross_unit_selling_price', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    gross_extended_amount: Mapped[str] = mapped_column('gross_extended_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amount_includes_tax_flag: Mapped[str] = mapped_column('amount_includes_tax_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    taxable_amount: Mapped[str] = mapped_column('taxable_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    warehouse_id: Mapped[str] = mapped_column('warehouse_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    translated_description: Mapped[str] = mapped_column('translated_description', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    extended_acctd_amount: Mapped[str] = mapped_column('extended_acctd_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    br_ref_customer_trx_id: Mapped[str] = mapped_column('br_ref_customer_trx_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    br_ref_payment_schedule_id: Mapped[str] = mapped_column('br_ref_payment_schedule_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    br_adjustment_id: Mapped[str] = mapped_column('br_adjustment_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    mrc_extended_acctd_amount: Mapped[str] = mapped_column('mrc_extended_acctd_amount', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    payment_set_id: Mapped[str] = mapped_column('payment_set_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    contract_line_id: Mapped[str] = mapped_column('contract_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    source_data_key1: Mapped[str] = mapped_column('source_data_key1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    source_data_key2: Mapped[str] = mapped_column('source_data_key2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    source_data_key3: Mapped[str] = mapped_column('source_data_key3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    source_data_key4: Mapped[str] = mapped_column('source_data_key4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    source_data_key5: Mapped[str] = mapped_column('source_data_key5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    invoiced_line_acctg_level: Mapped[str] = mapped_column('invoiced_line_acctg_level', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    override_auto_accounting_flag: Mapped[str] = mapped_column('override_auto_accounting_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_to_customer_id: Mapped[str] = mapped_column('ship_to_customer_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_to_address_id: Mapped[str] = mapped_column('ship_to_address_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_to_site_use_id: Mapped[str] = mapped_column('ship_to_site_use_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    ship_to_contact_id: Mapped[str] = mapped_column('ship_to_contact_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    historical_flag: Mapped[str] = mapped_column('historical_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_line_id: Mapped[str] = mapped_column('tax_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    line_recoverable: Mapped[str] = mapped_column('line_recoverable', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_recoverable: Mapped[str] = mapped_column('tax_recoverable', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_classification_code: Mapped[str] = mapped_column('tax_classification_code', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amount_due_remaining: Mapped[str] = mapped_column('amount_due_remaining', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    acctd_amount_due_remaining: Mapped[str] = mapped_column('acctd_amount_due_remaining', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    amount_due_original: Mapped[str] = mapped_column('amount_due_original', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    acctd_amount_due_original: Mapped[str] = mapped_column('acctd_amount_due_original', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    chrg_amount_remaining: Mapped[str] = mapped_column('chrg_amount_remaining', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    chrg_acctd_amount_remaining: Mapped[str] = mapped_column('chrg_acctd_amount_remaining', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    frt_adj_remaining: Mapped[str] = mapped_column('frt_adj_remaining', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    frt_adj_acctd_remaining: Mapped[str] = mapped_column('frt_adj_acctd_remaining', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    frt_ed_amount: Mapped[str] = mapped_column('frt_ed_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    frt_ed_acctd_amount: Mapped[str] = mapped_column('frt_ed_acctd_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    frt_uned_amount: Mapped[str] = mapped_column('frt_uned_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    frt_uned_acctd_amount: Mapped[str] = mapped_column('frt_uned_acctd_amount', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    deferral_exclusion_flag: Mapped[str] = mapped_column('deferral_exclusion_flag', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    rule_end_date: Mapped[str] = mapped_column('rule_end_date', Date, primary_key=False, info={"column_metadata": ColumnMetadata()})
    payment_trxn_extension_id: Mapped[str] = mapped_column('payment_trxn_extension_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    interest_line_id: Mapped[str] = mapped_column('interest_line_id', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    doc_line_id_int_1: Mapped[str] = mapped_column('doc_line_id_int_1', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    doc_line_id_int_2: Mapped[str] = mapped_column('doc_line_id_int_2', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    doc_line_id_int_3: Mapped[str] = mapped_column('doc_line_id_int_3', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    doc_line_id_int_4: Mapped[str] = mapped_column('doc_line_id_int_4', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    doc_line_id_int_5: Mapped[str] = mapped_column('doc_line_id_int_5', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})
    doc_line_id_char_1: Mapped[str] = mapped_column('doc_line_id_char_1', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    doc_line_id_char_2: Mapped[str] = mapped_column('doc_line_id_char_2', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    doc_line_id_char_3: Mapped[str] = mapped_column('doc_line_id_char_3', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    doc_line_id_char_4: Mapped[str] = mapped_column('doc_line_id_char_4', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    doc_line_id_char_5: Mapped[str] = mapped_column('doc_line_id_char_5', String, primary_key=False, info={"column_metadata": ColumnMetadata()})
    tax_calc_acctd_amt: Mapped[str] = mapped_column('tax_calc_acctd_amt', Integer, primary_key=False, info={"column_metadata": ColumnMetadata()})

        

    

    MtlSystemItemsB_inventory_item_id: Mapped["MtlSystemItemsB"] = relationship(back_populates="RaCustomerTrxLinesAll_inventory_item_id", primaryjoin="MtlSystemItemsB.inventory_item_id==RaCustomerTrxLinesAll.inventory_item_id", foreign_keys="[RaCustomerTrxLinesAll.inventory_item_id]", viewonly=True)
        

    

    MtlSystemItemsB_organization_id: Mapped["MtlSystemItemsB"] = relationship(back_populates="RaCustomerTrxLinesAll_warehouse_id", primaryjoin="MtlSystemItemsB.organization_id==RaCustomerTrxLinesAll.warehouse_id", foreign_keys="[RaCustomerTrxLinesAll.warehouse_id]", viewonly=True)
        

    

    RaCustomerTrxAll_customer_trx_id: Mapped["RaCustomerTrxAll"] = relationship(back_populates="RaCustomerTrxLinesAll_customer_trx_id", primaryjoin="RaCustomerTrxAll.customer_trx_id==RaCustomerTrxLinesAll.customer_trx_id", foreign_keys="[RaCustomerTrxLinesAll.customer_trx_id]", viewonly=True)



