from sqlalchemy import Date, Float, Integer, String, Numeric, DateTime, join, and_
from sqlalchemy.orm import Mapped, mapped_column, relationship, column_property
from efficieno.components.erd_objects import ERDBase, ColumnMetadata

from di_thermax_planmax.erd.inv.mtl_system_items_b import MtlSystemItemsB
from di_thermax_planmax.erd.ont.oe_order_lines_all import OeOrderLinesAll
from di_thermax_planmax.erd.apps.org_organization_definitions import OrgOrganizationDefinitions



class OrderLines(ERDBase):
    # __table__ = join(OeOrderHeadersAll, OrgOrganizationDefinitions, OeOrderHeadersAll.OrgOrganizationDefinitions_organization_id.expression)
    __table__ = (join(OeOrderLinesAll, OrgOrganizationDefinitions, OeOrderLinesAll.OrgOrganizationDefinitions_organization_id.expression)
                 .join(MtlSystemItemsB, and_(OeOrderLinesAll.MtlSystemItemsB_organization_id.expression, OeOrderLinesAll.MtlSystemItemsB_inventory_item_id.expression)))
                 # .join(MtlSystemItemsB, OeOrderLinesAll.MtlSystemItemsB_inventory_item_id.expression))
    __table_properties__ = {"ui_x_pos": 503.13734483912555, "ui_y_pos": 891.5731584714746, "colour": "#F2F3F5"}

    line_id = column_property(OeOrderLinesAll.line_id)
    organization_code = column_property(OrgOrganizationDefinitions.organization_code)
    segment1 = column_property(MtlSystemItemsB.segment1)
    org_id = column_property(OeOrderLinesAll.org_id)
    header_id = column_property(OeOrderLinesAll.header_id)
    line_type_id = column_property(OeOrderLinesAll.line_type_id)
    line_number = column_property(OeOrderLinesAll.line_number)
    ordered_item = column_property(OeOrderLinesAll.ordered_item)
    request_date = column_property(OeOrderLinesAll.request_date)
    promise_date = column_property(OeOrderLinesAll.promise_date)
    schedule_ship_date = column_property(OeOrderLinesAll.schedule_ship_date)
    order_quantity_uom = column_property(OeOrderLinesAll.order_quantity_uom)
    pricing_quantity = column_property(OeOrderLinesAll.pricing_quantity)
    pricing_quantity_uom = column_property(OeOrderLinesAll.pricing_quantity_uom)
    cancelled_quantity = column_property(OeOrderLinesAll.cancelled_quantity)
    shipped_quantity = column_property(OeOrderLinesAll.shipped_quantity)
    ordered_quantity = column_property(OeOrderLinesAll.ordered_quantity)
    fulfilled_quantity = column_property(OeOrderLinesAll.fulfilled_quantity)
    shipping_quantity = column_property(OeOrderLinesAll.shipping_quantity)
    shipping_quantity_uom = column_property(OeOrderLinesAll.shipping_quantity_uom)
    delivery_lead_time = column_property(OeOrderLinesAll.delivery_lead_time)
    tax_exempt_flag = column_property(OeOrderLinesAll.tax_exempt_flag)
    tax_exempt_number = column_property(OeOrderLinesAll.tax_exempt_number)
    tax_exempt_reason_code = column_property(OeOrderLinesAll.tax_exempt_reason_code)
    project_id = column_property(OeOrderLinesAll.project_id)
    task_id = column_property(OeOrderLinesAll.task_id)
    inventory_item_id = column_property(MtlSystemItemsB.inventory_item_id, OeOrderLinesAll.inventory_item_id)
    shipping_method_code = column_property(OeOrderLinesAll.shipping_method_code)
    freight_carrier_code = column_property(OeOrderLinesAll.freight_carrier_code)
    freight_terms_code = column_property(OeOrderLinesAll.freight_terms_code)
    fob_point_code = column_property(OeOrderLinesAll.fob_point_code)
    tax_point_code = column_property(OeOrderLinesAll.tax_point_code)
    item_revision = column_property(OeOrderLinesAll.item_revision)
    unit_selling_price = column_property(OeOrderLinesAll.unit_selling_price)
    unit_list_price = column_property(OeOrderLinesAll.unit_list_price)
    actual_shipment_date = column_property(OeOrderLinesAll.actual_shipment_date)
    cancelled_flag = column_property(OeOrderLinesAll.cancelled_flag)
    open_flag = column_property(OeOrderLinesAll.open_flag)
    booked_flag = column_property(OeOrderLinesAll.booked_flag)
    ship_from_org_id = column_property(OeOrderLinesAll.ship_from_org_id, OrgOrganizationDefinitions.organization_id)
    last_update_date = column_property(OeOrderLinesAll.last_update_date, MtlSystemItemsB.last_update_date)
    last_updated_by = column_property(OeOrderLinesAll.last_updated_by, MtlSystemItemsB.last_updated_by)
    creation_date = column_property(OeOrderLinesAll.creation_date, MtlSystemItemsB.creation_date)
    created_by = column_property(OeOrderLinesAll.created_by, MtlSystemItemsB.created_by)
    last_update_login = column_property(OeOrderLinesAll.last_update_login, MtlSystemItemsB.last_update_login)
    accounting_rule_id = column_property(OeOrderLinesAll.accounting_rule_id, MtlSystemItemsB.accounting_rule_id)
    invoicing_rule_id = column_property(OeOrderLinesAll.invoicing_rule_id, MtlSystemItemsB.invoicing_rule_id)
    attribute1 = column_property(OeOrderLinesAll.attribute1, MtlSystemItemsB.attribute1)
    attribute2 = column_property(OeOrderLinesAll.attribute2, MtlSystemItemsB.attribute2)
    attribute3 = column_property(OeOrderLinesAll.attribute3, MtlSystemItemsB.attribute3)
    attribute4 = column_property(OeOrderLinesAll.attribute4, MtlSystemItemsB.attribute4)
    attribute5 = column_property(OeOrderLinesAll.attribute5, MtlSystemItemsB.attribute5)
    attribute6 = column_property(OeOrderLinesAll.attribute6, MtlSystemItemsB.attribute6)
    attribute7 = column_property(OeOrderLinesAll.attribute7, MtlSystemItemsB.attribute7)
    attribute8 = column_property(OeOrderLinesAll.attribute8, MtlSystemItemsB.attribute8)
    attribute9 = column_property(OeOrderLinesAll.attribute9, MtlSystemItemsB.attribute9)
    attribute10 = column_property(OeOrderLinesAll.attribute10, MtlSystemItemsB.attribute10)
    attribute11 = column_property(OeOrderLinesAll.attribute11, MtlSystemItemsB.attribute11)
    attribute12 = column_property(OeOrderLinesAll.attribute12, MtlSystemItemsB.attribute12)
    attribute13 = column_property(OeOrderLinesAll.attribute13, MtlSystemItemsB.attribute13)
    attribute14 = column_property(OeOrderLinesAll.attribute14, MtlSystemItemsB.attribute14)
    attribute15 = column_property(OeOrderLinesAll.attribute15, MtlSystemItemsB.attribute15)
    attribute16 = column_property(OeOrderLinesAll.attribute16, MtlSystemItemsB.attribute16)
    attribute17 = column_property(OeOrderLinesAll.attribute17, MtlSystemItemsB.attribute17)
    attribute18 = column_property(OeOrderLinesAll.attribute18, MtlSystemItemsB.attribute18)
    attribute19 = column_property(OeOrderLinesAll.attribute19, MtlSystemItemsB.attribute19)
    attribute20 = column_property(OeOrderLinesAll.attribute20, MtlSystemItemsB.attribute20)
    service_duration = column_property(OeOrderLinesAll.service_duration, MtlSystemItemsB.service_duration)
    tax_code = column_property(OeOrderLinesAll.tax_code, MtlSystemItemsB.tax_code)
    request_id = column_property(OeOrderLinesAll.request_id, MtlSystemItemsB.request_id)
    program_application_id = column_property(OeOrderLinesAll.program_application_id, MtlSystemItemsB.program_application_id)
    program_id = column_property(OeOrderLinesAll.program_id, MtlSystemItemsB.program_id)
    program_update_date = column_property(OeOrderLinesAll.program_update_date, MtlSystemItemsB.program_update_date)
    ship_model_complete_flag = column_property(OeOrderLinesAll.ship_model_complete_flag, MtlSystemItemsB.ship_model_complete_flag)
    global_attribute_category = column_property(OeOrderLinesAll.global_attribute_category, MtlSystemItemsB.global_attribute_category)
    global_attribute1 = column_property(OeOrderLinesAll.global_attribute1, MtlSystemItemsB.global_attribute1)
    global_attribute2 = column_property(OeOrderLinesAll.global_attribute2, MtlSystemItemsB.global_attribute2)
    global_attribute3 = column_property(OeOrderLinesAll.global_attribute3, MtlSystemItemsB.global_attribute3)
    global_attribute4 = column_property(OeOrderLinesAll.global_attribute4, MtlSystemItemsB.global_attribute4)
    global_attribute5 = column_property(OeOrderLinesAll.global_attribute5, MtlSystemItemsB.global_attribute5)
    global_attribute6 = column_property(OeOrderLinesAll.global_attribute6, MtlSystemItemsB.global_attribute6)
    global_attribute7 = column_property(OeOrderLinesAll.global_attribute7, MtlSystemItemsB.global_attribute7)
    global_attribute8 = column_property(OeOrderLinesAll.global_attribute8, MtlSystemItemsB.global_attribute8)
    global_attribute9 = column_property(OeOrderLinesAll.global_attribute9, MtlSystemItemsB.global_attribute9)
    global_attribute10 = column_property(OeOrderLinesAll.global_attribute10, MtlSystemItemsB.global_attribute10)
    global_attribute11 = column_property(OeOrderLinesAll.global_attribute11, MtlSystemItemsB.global_attribute11)
    global_attribute12 = column_property(OeOrderLinesAll.global_attribute12, MtlSystemItemsB.global_attribute12)
    global_attribute13 = column_property(OeOrderLinesAll.global_attribute13, MtlSystemItemsB.global_attribute13)
    global_attribute14 = column_property(OeOrderLinesAll.global_attribute14, MtlSystemItemsB.global_attribute14)
    global_attribute15 = column_property(OeOrderLinesAll.global_attribute15, MtlSystemItemsB.global_attribute15)
    global_attribute16 = column_property(OeOrderLinesAll.global_attribute16, MtlSystemItemsB.global_attribute16)
    global_attribute17 = column_property(OeOrderLinesAll.global_attribute17, MtlSystemItemsB.global_attribute17)
    global_attribute18 = column_property(OeOrderLinesAll.global_attribute18, MtlSystemItemsB.global_attribute18)
    global_attribute19 = column_property(OeOrderLinesAll.global_attribute19, MtlSystemItemsB.global_attribute19)
    global_attribute20 = column_property(OeOrderLinesAll.global_attribute20, MtlSystemItemsB.global_attribute20)
    charge_periodicity_code = column_property(OeOrderLinesAll.charge_periodicity_code, MtlSystemItemsB.charge_periodicity_code)