from typing import TYPE_CHECKING

from sqlalchemy import Date, Float, Integer, String, Numeric, DateTime, join, outerjoin
from sqlalchemy.orm import Mapped, mapped_column, relationship, column_property
from efficieno.components.erd_objects import ERDBase, ColumnMetadata

from di_thermax_planmax.erd.xxtmx_planmax.xxplanmax_header_dtls import XxplanmaxHeaderDtls
from di_thermax_planmax.erd.xxtmx_planmax.xxplanmax_line_dtls import XxplanmaxLineDtls
from di_thermax_planmax.erd.xxtmx_planmax.xxplanmax_cust_dtls import XxplanmaxCustDtls
from di_thermax_planmax.erd.apps.org_organization_definitions import OrgOrganizationDefinitions
from di_thermax_planmax.erd.xxtmx_planmax.xxplanmax_calender import XxplanmaxCalender


class PlanmaxLines(ERDBase):
    # __table__ = (join(XxplanmaxHeaderDtls, XxplanmaxCustDtls, XxplanmaxHeaderDtls.XxplanmaxCustDtls_site_use_id.expression)
    #              .join(OrgOrganizationDefinitions, XxplanmaxHeaderDtls.OrgOrganizationDefinitions_organization_id.expression))
    __table__ = XxplanmaxLineDtls.__table__
    # __table__ = outerjoin(XxplanmaxHeaderDtls, XxplanmaxCalender, XxplanmaxHeaderDtls.XxplanmaxCalender_day_id.expression)
    __table_properties__ = {"ui_x_pos": 503.13734483912555, "ui_y_pos": 891.5731584714746, "colour": "#F2F3F5"}

    sales_order_header_id = column_property(XxplanmaxLineDtls.sales_order_header_id)
    sales_order_header = column_property(XxplanmaxLineDtls.sales_order_header)
    sales_order_line_id = column_property(XxplanmaxLineDtls.sales_order_line_id)
    sales_order_line = column_property(XxplanmaxLineDtls.sales_order_line)
    reference_line_id = column_property(XxplanmaxLineDtls.reference_line_id)
    reference_line = column_property(XxplanmaxLineDtls.reference_line)
    project_id = column_property(XxplanmaxLineDtls.project_id)
    organization_id = column_property(XxplanmaxLineDtls.organization_id)
    bill_sequence_id = column_property(XxplanmaxLineDtls.bill_sequence_id)
    bom_implementation_date = column_property(XxplanmaxLineDtls.bom_implementation_date)
    change_notice = column_property(XxplanmaxLineDtls.change_notice)
    common_bill_sequence_id = column_property(XxplanmaxLineDtls.common_bill_sequence_id)
    common_organization_id = column_property(XxplanmaxLineDtls.common_organization_id)
    assembly_item_id = column_property(XxplanmaxLineDtls.assembly_item_id)
    assembly_item = column_property(XxplanmaxLineDtls.assembly_item)
    assembly_item_type = column_property(XxplanmaxLineDtls.assembly_item_type)
    plan_level = column_property(XxplanmaxLineDtls.plan_level)
    effectivity_date = column_property(XxplanmaxLineDtls.effectivity_date)
    disable_date = column_property(XxplanmaxLineDtls.disable_date)
    item_num = column_property(XxplanmaxLineDtls.item_num)
    operation_seq_num = column_property(XxplanmaxLineDtls.operation_seq_num)
    implementation_date = column_property(XxplanmaxLineDtls.implementation_date)
    component_code = column_property(XxplanmaxLineDtls.component_code)
    component_item_id = column_property(XxplanmaxLineDtls.component_item_id)
    component_item = column_property(XxplanmaxLineDtls.component_item)
    component_item_revision_war = column_property(XxplanmaxLineDtls.component_item_revision_war)
    component_item_revision_en1 = column_property(XxplanmaxLineDtls.component_item_revision_en1)
    component_item_type = column_property(XxplanmaxLineDtls.component_item_type)
    component_quantity = column_property(XxplanmaxLineDtls.component_quantity)
    engg_org_exists = column_property(XxplanmaxLineDtls.engg_org_exists)
    warehouse_org_exists = column_property(XxplanmaxLineDtls.warehouse_org_exists)
    extended_quantity = column_property(XxplanmaxLineDtls.extended_quantity)
    component_shippable_item_flag = column_property(XxplanmaxLineDtls.component_shippable_item_flag)
    planning_make_buy_code = column_property(XxplanmaxLineDtls.planning_make_buy_code)
    primary_unit_of_measure = column_property(XxplanmaxLineDtls.primary_unit_of_measure)
    item_cost = column_property(XxplanmaxLineDtls.item_cost)
    line_item_type = column_property(XxplanmaxLineDtls.line_item_type)
    line_item_sub_type = column_property(XxplanmaxLineDtls.line_item_sub_type)
    project_number = column_property(XxplanmaxLineDtls.project_number)
    show_on_view = column_property(XxplanmaxLineDtls.show_on_view)
    order_line_item_type = column_property(XxplanmaxLineDtls.order_line_item_type)
    shippable_flag = column_property(XxplanmaxLineDtls.shippable_flag)
    po_number = column_property(XxplanmaxLineDtls.po_number)
    po_header_id = column_property(XxplanmaxLineDtls.po_header_id)
    po_line_num = column_property(XxplanmaxLineDtls.po_line_num)
    po_line_id = column_property(XxplanmaxLineDtls.po_line_id)
    po_line_location_id = column_property(XxplanmaxLineDtls.po_line_location_id)
    po_distribution_id = column_property(XxplanmaxLineDtls.po_distribution_id)
    po_auth_status = column_property(XxplanmaxLineDtls.po_auth_status)
    po_approved_date = column_property(XxplanmaxLineDtls.po_approved_date)
    po_line_qty = column_property(XxplanmaxLineDtls.po_line_qty)
    po_qty_received = column_property(XxplanmaxLineDtls.po_qty_received)
    po_qty_accepted = column_property(XxplanmaxLineDtls.po_qty_accepted)
    requisition_header_id = column_property(XxplanmaxLineDtls.requisition_header_id)
    req_preparer_id = column_property(XxplanmaxLineDtls.req_preparer_id)
    req_number = column_property(XxplanmaxLineDtls.req_number)
    req_auth_status = column_property(XxplanmaxLineDtls.req_auth_status)
    req_approved_date = column_property(XxplanmaxLineDtls.req_approved_date)
    requisition_line_id = column_property(XxplanmaxLineDtls.requisition_line_id)
    suggested_buyer_id = column_property(XxplanmaxLineDtls.suggested_buyer_id)
    req_distribution_id = column_property(XxplanmaxLineDtls.req_distribution_id)
    wip_entity_id = column_property(XxplanmaxLineDtls.wip_entity_id)
    wip_entity_name = column_property(XxplanmaxLineDtls.wip_entity_name)
    wip_job_type = column_property(XxplanmaxLineDtls.wip_job_type)
    wip_job_status = column_property(XxplanmaxLineDtls.wip_job_status)
    wip_job_class = column_property(XxplanmaxLineDtls.wip_job_class)
    wip_job_qty = column_property(XxplanmaxLineDtls.wip_job_qty)
    curr_onhand_qty = column_property(XxplanmaxLineDtls.curr_onhand_qty)
    task_id = column_property(XxplanmaxLineDtls.task_id)
    wip_required_quantity = column_property(XxplanmaxLineDtls.wip_required_quantity)
    wip_quantity_issued = column_property(XxplanmaxLineDtls.wip_quantity_issued)
    wip_quantity_pending = column_property(XxplanmaxLineDtls.wip_quantity_pending)
    wip_onhand = column_property(XxplanmaxLineDtls.wip_onhand)
    wip_reservation = column_property(XxplanmaxLineDtls.wip_reservation)
    bom_explosion_date = column_property(XxplanmaxLineDtls.bom_explosion_date)
