from typing import TYPE_CHECKING

from sqlalchemy import Date, Float, Integer, String, Numeric, DateTime, join
from sqlalchemy.orm import Mapped, mapped_column, relationship, column_property
from efficieno.components.erd_objects import ERDBase, ColumnMetadata

from di_thermax_planmax.erd.xxtmx_planmax.xxplanmax_header_dtls import XxplanmaxHeaderDtls
from di_thermax_planmax.erd.xxtmx_planmax.xxplanmax_cust_dtls import XxplanmaxCustDtls
from di_thermax_planmax.erd.apps.org_organization_definitions import OrgOrganizationDefinitions


class PlanmaxHeaders(ERDBase):
    __table__ = (join(XxplanmaxHeaderDtls, XxplanmaxCustDtls, XxplanmaxHeaderDtls.XxplanmaxCustDtls_site_use_id.expression)
                 .join(OrgOrganizationDefinitions, XxplanmaxHeaderDtls.OrgOrganizationDefinitions_organization_id.expression))
    __table_properties__ = {"ui_x_pos": 503.13734483912555, "ui_y_pos": 891.5731584714746, "colour": "#F2F3F5"}


    operating_unit_id = column_property(XxplanmaxHeaderDtls.operating_unit_id)
    sales_order_header_id = column_property(XxplanmaxHeaderDtls.sales_order_header_id)
    sales_order_number = column_property(XxplanmaxHeaderDtls.sales_order_number)
    model_line_id = column_property(XxplanmaxHeaderDtls.model_line_id)
    model_line_number = column_property(XxplanmaxHeaderDtls.model_line_number)
    order_type_id = column_property(XxplanmaxHeaderDtls.order_type_id)
    group_name = column_property(XxplanmaxHeaderDtls.group_name)
    sub_group = column_property(XxplanmaxHeaderDtls.sub_group)
    product_category = column_property(XxplanmaxHeaderDtls.product_category)
    prn_applicable = column_property(XxplanmaxHeaderDtls.prn_applicable)
    inspection_required = column_property(XxplanmaxHeaderDtls.inspection_required)
    project_id = column_property(XxplanmaxHeaderDtls.project_id)
    project_number = column_property(XxplanmaxHeaderDtls.project_number)
    std_nstd = column_property(XxplanmaxHeaderDtls.std_nstd)
    sos_item = column_property(XxplanmaxHeaderDtls.sos_item)
    mfg_organization_id = column_property(XxplanmaxHeaderDtls.mfg_organization_id)
    orig_cust_required_date = column_property(XxplanmaxHeaderDtls.orig_cust_required_date)
    curr_cust_required_date = column_property(XxplanmaxHeaderDtls.curr_cust_required_date)
    orig_thx_commitment_date = column_property(XxplanmaxHeaderDtls.orig_thx_commitment_date)
    curr_thx_commitment_date = column_property(XxplanmaxHeaderDtls.curr_thx_commitment_date)
    ho_order_commited_to = column_property(XxplanmaxHeaderDtls.ho_order_commited_to)
    ho_order_so_header = column_property(XxplanmaxHeaderDtls.ho_order_so_header)
    ho_order_so_line = column_property(XxplanmaxHeaderDtls.ho_order_so_line)
    oc_no = column_property(XxplanmaxHeaderDtls.oc_no)
    oc_date = column_property(XxplanmaxHeaderDtls.oc_date)
    tech_clarity_date = column_property(XxplanmaxHeaderDtls.tech_clarity_date)
    engg_commt_dt = column_property(XxplanmaxHeaderDtls.engg_commt_dt)
    oc_status = column_property(XxplanmaxHeaderDtls.oc_status)
    oc_closure_date = column_property(XxplanmaxHeaderDtls.oc_closure_date)
    planned_invoice_dates = column_property(XxplanmaxHeaderDtls.planned_invoice_dates)
    planned_invoice_value = column_property(XxplanmaxHeaderDtls.planned_invoice_value)
    wip_folder_release_date = column_property(XxplanmaxHeaderDtls.wip_folder_release_date)
    commissioning_date = column_property(XxplanmaxHeaderDtls.commissioning_date)
    site_release_date = column_property(XxplanmaxHeaderDtls.site_release_date)
    planner = column_property(XxplanmaxHeaderDtls.planner)
    tca = column_property(XxplanmaxHeaderDtls.tca)
    send_email = column_property(XxplanmaxHeaderDtls.send_email)
    fg_month_change_remarks = column_property(XxplanmaxHeaderDtls.fg_month_change_remarks)
    shell_boiler_appr_auth = column_property(XxplanmaxHeaderDtls.shell_boiler_appr_auth)
    reason_for_otp = column_property(XxplanmaxHeaderDtls.reason_for_otp)
    manual_ord_chg_status = column_property(XxplanmaxHeaderDtls.manual_ord_chg_status)
    order_status = column_property(XxplanmaxHeaderDtls.order_status)
    interface_status = column_property(XxplanmaxHeaderDtls.interface_status)
    creation_date = column_property(XxplanmaxHeaderDtls.creation_date)
    last_update_date = column_property(XxplanmaxHeaderDtls.last_update_date)
    refresh_date = column_property(XxplanmaxHeaderDtls.refresh_date)
    bill_site_use_id = column_property(XxplanmaxHeaderDtls.bill_site_use_id)
    bill_cust_acct_site_id = column_property(XxplanmaxHeaderDtls.bill_cust_acct_site_id)
    bill_party_site_id = column_property(XxplanmaxHeaderDtls.bill_party_site_id)
    bill_party_id = column_property(XxplanmaxHeaderDtls.bill_party_id)
    bill_location_id = column_property(XxplanmaxHeaderDtls.bill_location_id)
    ship_site_use_id = column_property(XxplanmaxHeaderDtls.ship_site_use_id)
    ship_cust_acct_site_id = column_property(XxplanmaxHeaderDtls.ship_cust_acct_site_id)
    ship_party_site_id = column_property(XxplanmaxHeaderDtls.ship_party_site_id)
    ship_party_id = column_property(XxplanmaxHeaderDtls.ship_party_id)
    ship_location_id = column_property(XxplanmaxHeaderDtls.ship_location_id)
    order_intake_status = column_property(XxplanmaxHeaderDtls.order_intake_status)
    bom_common_status = column_property(XxplanmaxHeaderDtls.bom_common_status)
    reflection_config_status = column_property(XxplanmaxHeaderDtls.reflection_config_status)
    mat_planning_status = column_property(XxplanmaxHeaderDtls.mat_planning_status)
    sourcing_status = column_property(XxplanmaxHeaderDtls.sourcing_status)
    commit_dates_status_mfg = column_property(XxplanmaxHeaderDtls.commit_dates_status_mfg)
    commit_dates_status_mat = column_property(XxplanmaxHeaderDtls.commit_dates_status_mat)
    mfg_job_folder_status = column_property(XxplanmaxHeaderDtls.mfg_job_folder_status)
    prn_status = column_property(XxplanmaxHeaderDtls.prn_status)
    eol_mat_avail_status = column_property(XxplanmaxHeaderDtls.eol_mat_avail_status)
    wip_pur_mat_status = column_property(XxplanmaxHeaderDtls.wip_pur_mat_status)
    project_segment1 = column_property(XxplanmaxHeaderDtls.project_segment1)
    project_description = column_property(XxplanmaxHeaderDtls.project_description)
    project_task_number = column_property(XxplanmaxHeaderDtls.project_task_number)
    project_task_id = column_property(XxplanmaxHeaderDtls.project_task_id)
    project_task_description = column_property(XxplanmaxHeaderDtls.project_task_description)
    operating_unit_name = column_property(XxplanmaxHeaderDtls.operating_unit_name)
    region_of_order = column_property(XxplanmaxHeaderDtls.region_of_order)
    type_of_order = column_property(XxplanmaxHeaderDtls.type_of_order)
    hdr_order_type = column_property(XxplanmaxHeaderDtls.hdr_order_type)
    hdr_booked_date = column_property(XxplanmaxHeaderDtls.hdr_booked_date)
    otm_tech_ocl_no = column_property(XxplanmaxHeaderDtls.otm_tech_ocl_no)
    fuel = column_property(XxplanmaxHeaderDtls.fuel)
    pressure = column_property(XxplanmaxHeaderDtls.pressure)
    special_instructions = column_property(XxplanmaxHeaderDtls.special_instructions)
    product_model = column_property(XxplanmaxHeaderDtls.product_model)
    ordered_date = column_property(XxplanmaxHeaderDtls.ordered_date)
    order_currency = column_property(XxplanmaxHeaderDtls.order_currency)
    total_unit_value = column_property(XxplanmaxHeaderDtls.total_unit_value)
    conversion_rate = column_property(XxplanmaxHeaderDtls.conversion_rate)
    total_unit_value_in_inr = column_property(XxplanmaxHeaderDtls.total_unit_value_in_inr)
    prn_customer_dely_date = column_property(XxplanmaxHeaderDtls.prn_customer_dely_date)
    prn_revised_dely_reqd_date = column_property(XxplanmaxHeaderDtls.prn_revised_dely_reqd_date)
    prn_number = column_property(XxplanmaxHeaderDtls.prn_number)
    prn_approved_date = column_property(XxplanmaxHeaderDtls.prn_approved_date)
    freight_pay = column_property(XxplanmaxHeaderDtls.freight_pay)
    inco_terms = column_property(XxplanmaxHeaderDtls.inco_terms)
    abp_percent = column_property(XxplanmaxHeaderDtls.abp_percent)
    pgb_percent = column_property(XxplanmaxHeaderDtls.pgb_percent)
    bonus = column_property(XxplanmaxHeaderDtls.bonus)
    ld_applicable = column_property(XxplanmaxHeaderDtls.ld_applicable)
    penalty = column_property(XxplanmaxHeaderDtls.penalty)
    insurance_by = column_property(XxplanmaxHeaderDtls.insurance_by)
    sales_engineer = column_property(XxplanmaxHeaderDtls.sales_engineer)
    otm_header_id = column_property(XxplanmaxHeaderDtls.otm_header_id)
    project_task_name = column_property(XxplanmaxHeaderDtls.project_task_name)
    proj_specific_llbom = column_property(XxplanmaxHeaderDtls.proj_specific_llbom)
    llbom_release_date = column_property(XxplanmaxHeaderDtls.llbom_release_date)
    llbom_pr = column_property(XxplanmaxHeaderDtls.llbom_pr)
    di_number = column_property(XxplanmaxHeaderDtls.di_number)
    di_date = column_property(XxplanmaxHeaderDtls.di_date)
    di_value = column_property(XxplanmaxHeaderDtls.di_value)
    di_freight = column_property(XxplanmaxHeaderDtls.di_freight)
    di_recommended_transporter = column_property(XxplanmaxHeaderDtls.di_recommended_transporter)
    di_transportation_scope = column_property(XxplanmaxHeaderDtls.di_transportation_scope)
    last_invoice_no = column_property(XxplanmaxHeaderDtls.last_invoice_no)
    last_invoice_date = column_property(XxplanmaxHeaderDtls.last_invoice_date)
    invoiced_value = column_property(XxplanmaxHeaderDtls.invoiced_value)
    contractual_plan_otp = column_property(XxplanmaxHeaderDtls.contractual_plan_otp)
    delivery_otp = column_property(XxplanmaxHeaderDtls.delivery_otp)
    original_project_no = column_property(XxplanmaxHeaderDtls.original_project_no)
    rated_standard_man_hrs = column_property(XxplanmaxHeaderDtls.rated_standard_man_hrs)
    mfg_commitment_date = column_property(XxplanmaxHeaderDtls.mfg_commitment_date)
    plan_eol_mech_date = column_property(XxplanmaxHeaderDtls.plan_eol_mech_date)
    plan_eol_ei_date = column_property(XxplanmaxHeaderDtls.plan_eol_ei_date)
    folder_status = column_property(XxplanmaxHeaderDtls.folder_status)
    regional_commercial = column_property(XxplanmaxHeaderDtls.regional_commercial)
    actual_fg_date = column_property(XxplanmaxHeaderDtls.actual_fg_date)
    shop_subcontract = column_property(XxplanmaxHeaderDtls.shop_subcontract)
    oc_required = column_property(XxplanmaxHeaderDtls.oc_required)
    suggested_plan_date = column_property(XxplanmaxHeaderDtls.suggested_plan_date)
    line_attribute9 = column_property(XxplanmaxHeaderDtls.line_attribute9)
    sos_en1_revision = column_property(XxplanmaxHeaderDtls.sos_en1_revision)
    sos_mfg_revision = column_property(XxplanmaxHeaderDtls.sos_mfg_revision)
    sos_revision_date = column_property(XxplanmaxHeaderDtls.sos_revision_date)
    mfg_organization_code = column_property(XxplanmaxHeaderDtls.mfg_organization_code)
    customer_name = column_property(XxplanmaxHeaderDtls.customer_name)
    account_number = column_property(XxplanmaxHeaderDtls.account_number, XxplanmaxCustDtls.account_number)
    prn_creation_status = column_property(XxplanmaxHeaderDtls.prn_creation_status)
    manual_order_status = column_property(XxplanmaxHeaderDtls.manual_order_status)
    ordered_item = column_property(XxplanmaxHeaderDtls.ordered_item)
    ordered_item_id = column_property(XxplanmaxHeaderDtls.ordered_item_id)
    sos_item_id = column_property(XxplanmaxHeaderDtls.sos_item_id)
    reflection_completion_date = column_property(XxplanmaxHeaderDtls.reflection_completion_date)
