from typing import TYPE_CHECKING

from sqlalchemy import Date, Float, Integer, String, Numeric, DateTime, join
from sqlalchemy.orm import Mapped, mapped_column, relationship, column_property
from efficieno.components.erd_objects import ERDBase, ColumnMetadata

from di_thermax_planmax.erd.xxtmx_planmax.xxplanmax_header_dtls import XxplanmaxHeaderDtls
from di_thermax_planmax.erd.xxtmx_planmax.xxplanmax_cust_dtls import XxplanmaxCustDtls
from di_thermax_planmax.erd.apps.org_organization_definitions import OrgOrganizationDefinitions
from di_thermax_planmax.erd.xxtmx_planmax.xxplanmax_calender import XxplanmaxCalender
from di_thermax_planmax.erd.xxtmx_planmax.xxplanmax_drp_details import XxplanmaxDrpDetails
from di_thermax_planmax.erd.xxtmx.xxtmx_tech_ocl_mstr_tbl import XxtmxTechOclMstrTbl
from di_thermax_planmax.erd.xxtmx.xxtmx_tech_ocl_specs_tbl import XxtmxTechOclSpecsTbl
from di_thermax_planmax.erd.apps.q_di_domestic_heating_v import QDiDomesticHeatingV


class QPDIDetails(ERDBase):
  
    __table__ = QDiDomesticHeatingV.__table__
    # __table__ = join(XxplanmaxHeaderDtls, XxplanmaxCalender, XxplanmaxHeaderDtls.XxplanmaxCalender_day_id.expression)
    __table_properties__ = {"ui_x_pos": 503.13734483912555, "ui_y_pos": 891.5731584714746, "colour": "#F2F3F5"}  
  
    plan_id = column_property(QDiDomesticHeatingV.plan_id)
    plan_name = column_property(QDiDomesticHeatingV.plan_name)
    organization_id = column_property(QDiDomesticHeatingV.organization_id)
    organization_name = column_property(QDiDomesticHeatingV.organization_name)
    collection_id = column_property(QDiDomesticHeatingV.collection_id)
    occurrence = column_property(QDiDomesticHeatingV.occurrence)
    last_update_date = column_property(QDiDomesticHeatingV.last_update_date)
    last_updated_by_id = column_property(QDiDomesticHeatingV.last_updated_by_id)
    last_updated_by = column_property(QDiDomesticHeatingV.last_updated_by)
    creation_date = column_property(QDiDomesticHeatingV.creation_date)
    created_by_id = column_property(QDiDomesticHeatingV.created_by_id)
    created_by = column_property(QDiDomesticHeatingV.created_by)
    last_update_login = column_property(QDiDomesticHeatingV.last_update_login)
    operating_unit = column_property(QDiDomesticHeatingV.operating_unit)
    di_number = column_property(QDiDomesticHeatingV.di_number)
    sales_order_no = column_property(QDiDomesticHeatingV.sales_order_no)
    customer_id = column_property(QDiDomesticHeatingV.customer_id)
    customer = column_property(QDiDomesticHeatingV.customer)
    xx_project_number = column_property(QDiDomesticHeatingV.xx_project_number)
    region_zone = column_property(QDiDomesticHeatingV.region_zone)
    area_country = column_property(QDiDomesticHeatingV.area_country)
    partial_shipment_instructions = column_property(QDiDomesticHeatingV.partial_shipment_instructions)
    bill_to_address = column_property(QDiDomesticHeatingV.bill_to_address)
    bill_to_customer_person_name = column_property(QDiDomesticHeatingV.bill_to_customer_person_name)
    ship_to_address = column_property(QDiDomesticHeatingV.ship_to_address)
    ship_to_customer_name = column_property(QDiDomesticHeatingV.ship_to_customer_name)
    tin_no = column_property(QDiDomesticHeatingV.tin_no)
    cust_ecc_no = column_property(QDiDomesticHeatingV.cust_ecc_no)
    cst_no = column_property(QDiDomesticHeatingV.cst_no)
    epcg_licence_number_date = column_property(QDiDomesticHeatingV.epcg_licence_number_date)
    contact_person = column_property(QDiDomesticHeatingV.contact_person)
    contact_number = column_property(QDiDomesticHeatingV.contact_number)
    fax = column_property(QDiDomesticHeatingV.fax)
    email_address = column_property(QDiDomesticHeatingV.email_address)
    receiver = column_property(QDiDomesticHeatingV.receiver)
    payment_amount = column_property(QDiDomesticHeatingV.payment_amount)
    br_cheque_number = column_property(QDiDomesticHeatingV.br_cheque_number)
    br_cheque_date = column_property(QDiDomesticHeatingV.br_cheque_date)
    recommended_transporter = column_property(QDiDomesticHeatingV.recommended_transporter)
    freight = column_property(QDiDomesticHeatingV.freight)
    consignment_delivery_instructn = column_property(QDiDomesticHeatingV.consignment_delivery_instructn)
    shipping_method = column_property(QDiDomesticHeatingV.shipping_method)
    MODE = column_property(QDiDomesticHeatingV.MODE)
    road_permit_status = column_property(QDiDomesticHeatingV.road_permit_status)
    payment_details1 = column_property(QDiDomesticHeatingV.payment_details1)
    amt1 = column_property(QDiDomesticHeatingV.amt1)
    payment_details2 = column_property(QDiDomesticHeatingV.payment_details2)
    amt2 = column_property(QDiDomesticHeatingV.amt2)
    payment_details3 = column_property(QDiDomesticHeatingV.payment_details3)
    amt3 = column_property(QDiDomesticHeatingV.amt3)
    payment_details4 = column_property(QDiDomesticHeatingV.payment_details4)
    amt4 = column_property(QDiDomesticHeatingV.amt4)
    total_amount = column_property(QDiDomesticHeatingV.total_amount)
    particulars1 = column_property(QDiDomesticHeatingV.particulars1)
    qty1 = column_property(QDiDomesticHeatingV.qty1)
    amt6 = column_property(QDiDomesticHeatingV.amt6)
    particulars2 = column_property(QDiDomesticHeatingV.particulars2)
    qty2 = column_property(QDiDomesticHeatingV.qty2)
    amt7 = column_property(QDiDomesticHeatingV.amt7)
    particulars3 = column_property(QDiDomesticHeatingV.particulars3)
    qty3 = column_property(QDiDomesticHeatingV.qty3)
    amt8 = column_property(QDiDomesticHeatingV.amt8)
    particulars4 = column_property(QDiDomesticHeatingV.particulars4)
    qty4 = column_property(QDiDomesticHeatingV.qty4)
    amt12 = column_property(QDiDomesticHeatingV.amt12)
    particulars5 = column_property(QDiDomesticHeatingV.particulars5)
    qty5 = column_property(QDiDomesticHeatingV.qty5)
    amt14 = column_property(QDiDomesticHeatingV.amt14)
    particulars6 = column_property(QDiDomesticHeatingV.particulars6)
    qty6 = column_property(QDiDomesticHeatingV.qty6)
    amt15 = column_property(QDiDomesticHeatingV.amt15)
    particulars7 = column_property(QDiDomesticHeatingV.particulars7)
    qty7 = column_property(QDiDomesticHeatingV.qty7)
    amt16 = column_property(QDiDomesticHeatingV.amt16)
    basic_amount = column_property(QDiDomesticHeatingV.basic_amount)
    packing__forwarding_amount = column_property(QDiDomesticHeatingV.packing__forwarding_amount)
    excisable_amount = column_property(QDiDomesticHeatingV.excisable_amount)
    excise__duty = column_property(QDiDomesticHeatingV.excise__duty)
    amt17 = column_property(QDiDomesticHeatingV.amt17)
    cess_on_excise__duty = column_property(QDiDomesticHeatingV.cess_on_excise__duty)
    amt9 = column_property(QDiDomesticHeatingV.amt9)
    s_h_cess_on_excise__duty = column_property(QDiDomesticHeatingV.s_h_cess_on_excise__duty)
    amt10 = column_property(QDiDomesticHeatingV.amt10)
    insurance_charges = column_property(QDiDomesticHeatingV.insurance_charges)
    taxable_amount = column_property(QDiDomesticHeatingV.taxable_amount)
    cst = column_property(QDiDomesticHeatingV.cst)
    amt5 = column_property(QDiDomesticHeatingV.amt5)
    vat = column_property(QDiDomesticHeatingV.vat)
    amt13 = column_property(QDiDomesticHeatingV.amt13)
    full_taxes = column_property(QDiDomesticHeatingV.full_taxes)
    amt11 = column_property(QDiDomesticHeatingV.amt11)
    freight_amount = column_property(QDiDomesticHeatingV.freight_amount)
    service_tax = column_property(QDiDomesticHeatingV.service_tax)
    service_tax_amount = column_property(QDiDomesticHeatingV.service_tax_amount)
    gross_amount = column_property(QDiDomesticHeatingV.gross_amount)
    unloading_by = column_property(QDiDomesticHeatingV.unloading_by)
    any_special_instruction = column_property(QDiDomesticHeatingV.any_special_instruction)
    send_email = column_property(QDiDomesticHeatingV.send_email)
    cgst = column_property(QDiDomesticHeatingV.cgst)
    cgst_percentage = column_property(QDiDomesticHeatingV.cgst_percentage)
    sgst = column_property(QDiDomesticHeatingV.sgst)
    sgst_percentage = column_property(QDiDomesticHeatingV.sgst_percentage)
